"""Writes analysis/parry/report.md from analysis/parry/results/ (no number is typed by hand).
Run: python -I analysis/parry/make_report.py
"""
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import numpy as np
import lib2b as L

R = L.RESULTS
OUT = L.HERE / "report.md"
TEAM_LABEL = {"cornell": "Cornell live text (written)", "press_pooled": "press answers, pooled", "press_federer": "press: Federer",
              "press_djokovic": "press: Djokovic", "press_murray": "press: Murray", "press_nadal": "press: Nadal"}


def lab(t):
    return TEAM_LABEL.get(t, L.short(t))


def f(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return float("nan")


def pc(x, d=1):
    v = f(x)
    return "-" if v != v else f"{100 * v:.{d}f}"


def ci(lo, hi, d=1, scale=100):
    a, b = f(lo), f(hi)
    if a != a or b != b:
        return ""
    return f"[{scale * a:.{d}f}, {scale * b:.{d}f}]"


def num(x, d=3):
    v = f(x)
    return "-" if v != v else f"{v:.{d}f}"


def pval(p):
    v = f(p)
    if v != v:
        return "-"
    return f"{v:.4f}" if v >= 0.0001 else f"{v:.1e}"


def table(head, rows):
    out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    for r in rows:
        out.append("| " + " | ".join(str(x) for x in r) + " |")
    return "\n".join(out)


def git_plan_commit():
    try:
        h = subprocess.run(["git", "log", "--diff-filter=A", "--format=%h %ad", "--date=iso", "--", "analysis/parry/plan.md"],
                           cwd=L.ROOT, capture_output=True, text=True, check=True).stdout.strip().splitlines()
        return h[-1] if h else "unknown"
    except Exception:  # noqa: BLE001
        return "unknown"


def main():
    S = []
    w = S.append
    meta = L.read_json(R / "sharing_meta.json")
    agg = L.read_csv(R / "sharing_aggregates.csv")
    A = {(r["S"], r["tokens"], r["measure"], r["statistic"]): r for r in agg}
    prim = {r["id"]: r for r in L.read_csv(R / "primary_tests.csv")}
    h12 = L.read_json(R / "primary_H1H2.json")
    h45 = L.read_json(R / "primary_H4H5.json")
    core = L.read_csv(R / "core_sizes.csv")
    core_meta = L.read_json(R / "core_meta.json")
    idio = L.read_csv(R / "idiolect_shares.csv")
    cbase = L.read_csv(R / "core_baselines.csv")
    ctop = L.read_csv(R / "core_top.csv")
    clus = L.read_csv(R / "cluster_tests.csv")
    qap = L.read_csv(R / "qap_regression.csv")
    pair = L.read_json(R / "pair_2019_2023.json")
    p2t = L.read_csv(R / "pool_to_target.csv")
    p2t_meta = L.read_json(R / "pool_to_target_meta.json")
    rsum = L.read_json(R / "refexpr_pool_summary.json")
    cats = L.read_csv(R / "refexpr_category_shares.csv")
    econ = L.read_csv(R / "refexpr_economy.csv")
    parr = L.read_csv(R / "parryan_pattern.csv")
    thr = L.read_csv(R / "thrift_tests_2b.csv")
    mde = L.read_csv(R / "mde_h4b.csv")
    ext = L.read_csv(R / "extension_2b.csv")
    e1 = L.read_csv(R / "e1_economy.csv")
    e1top = L.read_csv(R / "e1_top_types.csv")
    e2 = L.read_csv(R / "e2_classes.csv")
    e2t = L.read_csv(R / "e2_tests.csv")
    e1t = L.read_csv(R / "e1_tests.csv")
    h4d = L.read_csv(R / "h4_declustered.csv")
    h4s = L.read_csv(R / "h4b_by_slot.csv")
    tmeta = L.read_json(R / "thrift_meta.json")
    inv_full = L.read_csv(R / "inventory_sizes_full.csv")
    inv_m = L.read_csv(R / "inventory_sizes_matched.csv")
    slot_tok = L.read_csv(R / "slot_token_counts.csv")
    cal_ok = (R / "calibration_agreement.json").exists()
    teams = meta["teams"]
    tv_tokens = sum(teams[s]["tokens"] for s in L.TV)
    n_fps_bad = sum(1 for s, d in rsum["streams"].items() if not d["fps_valid"])

    def a(Sv, m, st, tok="norm"):
        return A[(str(Sv), tok, m, st)]

    def est_ci(Sv, m, st, tok="norm", d=1):
        r = a(Sv, m, st, tok)
        return f"{pc(r['estimate'], d)} {ci(r['ci_lo'], r['ci_hi'], d)}"

    # ------------------------------------------------------------------ header
    w("# Phase 2b: the tradition across broadcasts (shared stock, calibration, thrift per slot)")
    w("")
    w("Generated by `analysis/parry/make_report.py` from `analysis/parry/results/`; rerun everything with `bash analysis/parry/run_all.sh`. "
      f"The plan `analysis/parry/plan.md` was committed before any 2b test script was written or run (commit {git_plan_commit()}). "
      "**All of Phase 2b is exploratory relative to the pre-registered Phase 2**: it was added after every Phase 2 result had been seen, on the same corpus. "
      "Within 2b, seven tests were fixed in the plan as **2b-primary** and are Holm-corrected together (section 5); every other number is exploratory, "
      "and p-values outside section 5 are unadjusted. Brackets are 95% intervals; the kind of interval is stated each time. "
      "Post hoc changes made after a first look at outputs are listed in section 7.")
    w("")
    w("**What is measured.** As in Phase 2, 'formula' below means an exact word n-gram repeated in at least two utterances of a text "
      "(a repetition statistic), not Parry's metrically conditioned formula; the calibration in section 3 measures how far that statistic agrees with "
      "judgements of formulaicity by two LLM coders working from Parry's definition. A TV 'team' is one stream: one match with one unnamed broadcaster; "
      "team, match and broadcaster are confounded, and every commentator hint is [unverified].")
    w("")
    # ------------------------------------------------------------------ key results
    w("## Key results")
    w("")
    h1a, h1b, h2a, h2b = (h12[k] for k in ("H1a", "H1b", "H2a", "H2b"))
    w(f"* **Shared multiword stock (H1).** At 1,500 tokens per team, the formulas of one TV stream cover on average {pc(h1a['obs_mean'])}% of another TV stream's "
      f"tokens (n >= 2, player names and numerals normalised), against {pc(h1a['null_mean'])}% when both texts are unigram-shuffled: excess "
      f"{pc(h1a['estimate'])} percentage points {ci(h1a['ci_lo'], h1a['ci_hi'])} (bootstrap over the 20 streams), positive for {h1a['n_targets_positive']} of "
      f"{h1a['n_targets']} targets. For n >= 3 the coverage is {pc(h1b['obs_mean'], 2)}% and the excess {pc(h1b['estimate'], 2)} pp {ci(h1b['ci_lo'], h1b['ci_hi'], 2)}. "
      f"At 3,000 tokens: excess {est_ci(3000, 'cov_base', 'TV->TV mean excess')} pp (n >= 2), {est_ci(3000, 'cov_n3', 'TV->TV mean excess', d=2)} pp (n >= 3).")
    w(f"* **Is the stock specific to TV commentary (H2)?** For n >= 2, TV sources exceed the written live-text source by {pc(h2a['estimate'], 2)} pp "
      f"{ci(h2a['ci_lo'], h2a['ci_hi'], 2)} and the press-answer source by {pc(h2b['estimate'], 2)} pp {ci(h2b['ci_lo'], h2b['ci_hi'], 2)} in excess coverage of TV "
      f"targets ({h2a['n_targets_positive']} and {h2b['n_targets_positive']} of 20 targets positive), i.e. by about a quarter of the TV-TV excess. For n >= 3 the "
      f"differences are {est_ci(1500, 'cov_n3', 'TV->TV minus cornell->TV excess', d=2)} (Cornell) and {est_ci(1500, 'cov_n3', 'TV->TV minus press_pooled->TV excess', d=2)} "
      f"(press) pp at 1,500 tokens and {est_ci(3000, 'cov_n3', 'TV->TV minus cornell->TV excess', d=2)} and {est_ci(3000, 'cov_n3', 'TV->TV minus press_pooled->TV excess', d=2)} "
      "pp at 3,000: the TV-specific part of the shared stock is almost entirely two-word units. Without the `<name>`/`<num>` normalisation the n >= 2 differences shrink to "
      f"{est_ci(1500, 'cov_base', 'TV->TV minus cornell->TV excess', 'raw', 2)} and {est_ci(1500, 'cov_base', 'TV->TV minus press_pooled->TV excess', 'raw', 2)} pp, "
      "so a large part of it consists of frames around player names and numbers (score calls, `from <name>`, `for <name>`).")
    k20 = next(r for r in core if r["size"] == "full" and r["tokens"] == "norm" and r["k"] == "20")
    k10 = next(r for r in core if r["size"] == "full" and r["tokens"] == "norm" and r["k"] == "10")
    cb10 = {r["baseline"]: r for r in cbase if r["k"] == "10"}
    w(f"* **Genre core.** {int(f(k20['types_base']))} n-grams are formulas of all 20 teams and {int(f(k10['types_base']))} of at least 10 "
      f"({int(f(k10['types_n3']))} of them with n >= 3; none with n >= 3 is in all 20). Of the >= 10-team core, {pc(cb10['cornell']['share_in_baseline_inventory'], 0)}% "
      f"are formulas of a Cornell sample and {pc(cb10['press_pooled']['share_in_baseline_inventory'], 0)}% of a press sample of the same total size "
      f"({tv_tokens:,} tokens): the cross-broadcast core is mostly shared tennis English, not a commentary-only stock.")
    ia = [r for r in idio if r["size"].startswith("matched") and r["slot"] == "ALL"]
    by_slot = defaultdict(list)
    for r in idio:
        if r["size"].startswith("matched"):
            by_slot[r["slot"]].append(f(r["share_idiolect"]))
    w(f"* **Idiolect.** At 1,500 tokens, {pc(np.mean([f(r['share_idiolect']) for r in ia]))}% of a stream's formula tokens (mean over streams; range "
      f"{pc(min(f(r['share_idiolect']) for r in ia))}-{pc(max(f(r['share_idiolect']) for r in ia))}%) lie only in formulas that no other stream uses; by slot the share "
      f"is lowest for SCORE ({pc(np.mean(by_slot['SCORE']))}%) and highest for STAT ({pc(np.mean(by_slot['STAT']))}%). At matched size the idiolect share falls with "
      f"the stream's total length (Spearman rho {num(core_meta['spearman_idiolect_vs_stream_tokens']['matched'][0], 2)}), so part of it reflects how "
      "concentrated a 1,500-token sample of a short broadcast is, not the team.")
    slam = next(r for r in clus if r["similarity"] == "excess_cov_sym" and r["label"] == "slam")
    hint = next(r for r in clus if r["similarity"] == "excess_cov_sym" and r["label"].startswith("hint"))
    mp = next(r for r in clus if r["similarity"] == "jaccard_obs" and r["label"].startswith("Mantel r with shared"))
    w(f"* **Clusters (exploratory).** Pairs from the same slam share more (excess {pc(slam['within_minus_between'], 2)} pp above other pairs; permutation "
      f"p = {pval(slam['p_one_sided_higher_within'])}), which mixes broadcaster with venue and surface vocabulary. The only commentator-hint cluster with two members "
      f"(the 2019 and 2023 Wimbledon finals, 'Tim') ranks {pair['excess_cov_sym']['rank_among_190_pairs']} of {pair['excess_cov_sym']['n_pairs']} pairs "
      f"(p = {pval(hint['p_one_sided_higher_within'])}): no sign that the hinted team shares more. Inventory overlap rises with shared players "
      f"(Mantel r = {num(mp['within_minus_between'], 2)}, p = {pval(mp['p_one_sided_higher_within'])}).")
    loo19 = next(r for r in p2t if r["mode"] == "pool18" and r["target"] == L.MAIN)
    w(f"* **Is the 2019 figure typical?** With the other 19 streams as identification set, 2019's coverage (raw tokens, n >= 2) ranks "
      f"{p2t_meta['rank_2019_loo19_raw_base']} of {p2t_meta['n_targets']} (median {pc(p2t_meta['median_loo19_raw_base'])}%, range "
      f"{pc(p2t_meta['range_loo19_raw_base'][0])}-{pc(p2t_meta['range_loo19_raw_base'][1])}%); the Phase 2 value with the 18-stream pool is reproduced "
      f"({pc(loo19['base'], 2)}%).")
    if cal_ok:
        ca = L.read_json(R / "calibration_agreement.json")
        cm = L.read_json(R / "calibration_meta.json")
        cp = {(r["measure"], r["reference"], r["coder_confidence"]): r for r in L.read_csv(R / "calibration_prf.csv")}
        pm = ca["primary_HIGH_MEDIUM"]
        x = cp[("pool_n2", "A_or_B", "HIGH+MEDIUM")]
        y = cp[("pool_n3", "A_and_B", "HIGH+MEDIUM")]
        w(f"* **Calibration (2b.2; coders are LLM agents).** Token-level agreement between the two coders on 'inside a HIGH/MEDIUM formula span': "
          f"kappa = {num(pm['token_kappa'], 2)} {ci(pm['token_kappa_ci'][0], pm['token_kappa_ci'][1], 2, 1)}; they mark {pc(pm['positive_token_share_A'], 0)}% and "
          f"{pc(pm['positive_token_share_B'], 0)}% of tokens; span F1 {num(pm['span_F1_overlap'], 2)} (overlap) and "
          f"{num(pm['span_F1_exact'], 2)} (exact boundaries). The Phase 2 measure (pool n >= 2) marks {pc(x['auto_positive_share'], 0)}% of tokens and has precision {num(x['precision'], 2)} and recall {num(x['recall'], 2)} "
          f"against the union of the coders; pool n >= 3 against their intersection: precision {num(y['precision'], 2)}, recall {num(y['recall'], 2)}. "
          f"The slot classifier agrees with coder A's slot labels on {pc(cm['classifier_vs_coder']['A']['agreement'], 0)}% of spans "
          f"(kappa {num(cm['classifier_vs_coder']['A']['kappa'], 2)}) and with coder B's on {pc(cm['classifier_vs_coder']['B']['agreement'], 0)}% "
          f"(kappa {num(cm['classifier_vs_coder']['B']['kappa'], 2)}).")
    else:
        w("* **Calibration (2b.2).** Not run: the coders' files were absent when this report was generated (section 3).")
    allc = next(r for r in cats if r["team"] == "ALL_TV" and r["references"] == "commentary_only")
    pat = Counter(r["verdict"] for r in parr if r["slot_type"] == "situational")
    h4a, h4b, h5 = h45["H4a"], h45["H4b"], h45["H5"]
    d_dec = next(r for r in h4d if r["test"] == "H4b" and r["token_set"].startswith("first"))
    sl_sorted = sorted(h4s, key=lambda r: f(r["obs_minus_null"]))
    h4b_rej = prim["H4b"]["reject_holm_0.05"] == "True"
    mde_txt = (f"a planted slot-specific form in {pc(h4b['mde_theta_80pct_power'], 0)}% of references is detected with 80% power"
               if h4b.get("mde_theta_80pct_power") is not None else "the power simulation did not reach 80% on its grid")
    if h4b_rej:
        h4b_txt = (f"Within a team, the form depends weakly on the situational slot: H4b {h4b['D_obs']} distinct team x player x slot forms against "
                   f"{num(h4b['null_mean'], 1)} expected (p = {pval(h4b['p_one_sided_fewer'])}, Holm p = {pval(prim['H4b']['p_holm'])}; post hoc with one reference per "
                   f"player per utterance {d_dec['D_obs']} vs {num(d_dec['null_mean'], 1)}, p = {pval(d_dec['p_one_sided_fewer'])}); the deficit is "
                   f"{100 * (1 - h4b['D_obs'] / h4b['null_mean']):.1f}% of the expected count and lies mainly in "
                   + ", ".join(f"{r['slot']} ({num(r['distinct_obs'], 0)} vs {num(r['null_mean'], 1)})" for r in sl_sorted[:2])
                   + f" contexts ({mde_txt}).")
    else:
        h4b_txt = (f"Within a team, form choice does not depend on the situational slot beyond chance (H4b {h4b['D_obs']} vs {num(h4b['null_mean'], 1)}, "
                   f"p = {pval(h4b['p_one_sided_fewer'])}; {mde_txt}).")
    w(f"* **Naming and thrift (H4).** Over {allc['resolved_tokens']} commentary-only references to the players, the bare surname is "
      f"{pc(allc['share_surname'], 0)}%, the first name {pc(allc['share_first_name'], 0)}%, the full name {pc(allc['share_full_name'], 0)}%, hypocoristics "
      f"{pc(allc['share_hypocoristic'], 0)}% and descriptive epithets {pc(allc['share_epithet'], 0)}% (at most {pc(allc['share_epithet_upper'], 0)}% if every "
      f"unresolved epithet referred to a player). Teams differ in their naming habits (H4a: {h4a['D_obs']} distinct team x slot x category cells against "
      f"{num(h4a['null_mean'], 1)} expected if categories were assigned to teams at random; p = {pval(h4a['p_one_sided_fewer'])}; e.g. first names are "
      f"{pc(min(f(r['share_first_name']) for r in cats if r['references'] == 'commentary_only' and r['team'] != 'ALL_TV'), 0)}-"
      f"{pc(max(f(r['share_first_name']) for r in cats if r['references'] == 'commentary_only' and r['team'] != 'ALL_TV'), 0)}% of references by team). "
      + h4b_txt + " No team shows the Parryan pattern of one form per slot with different forms in different slots (situational slots: "
      + "; ".join(f"{k}: {v} teams" for k, v in sorted(pat.items())) + "); the economy that exists is the surname used almost everywhere.")
    sig2 = sorted([r for r in e2t if r.get("D_obs") and f(r["p_one_sided_fewer"]) < 0.05], key=lambda r: f(r["p_one_sided_fewer"]))
    nonsig2 = [r["class"] for r in e2t if r.get("D_obs") and f(r["p_one_sided_fewer"]) >= 0.05]
    w(f"* **Functional equivalents (E2, exploratory).** Of {sum(1 for r in e2t if r.get('D_obs'))} declared equivalence classes, team choice among the "
      f"alternatives is more consistent within teams than chance (unadjusted p < 0.05) for " + ", ".join(f"{r['class']} (p = {pval(r['p_one_sided_fewer'])})" for r in sig2)
      + f"; not for {', '.join(nonsig2)}. Unit choice for serve speed (miles vs kilometres per hour) is the clearest broadcaster habit; the commonest "
      "evaluative and hedging alternants are shared across teams.")
    w(f"* **Extension (H5).** No association was detected between the syllable length of a reference and the time available after its clip: weighted within-stream rho = {num(h5['rho_weighted'], 3)} "
      f"(stream bootstrap {ci(h5['boot_lo'], h5['boot_hi'], 3, 1)}; permutation p = {pval(h5['p_two'])}; {h5['tokens']} references in {h5['streams']} streams); "
      f"the minimum detectable rho at this N is about {num(h5['mde_rho_approx'], 3)}.")
    rej = [k for k, r in prim.items() if r["reject_holm_0.05"] == "True"]
    w(f"* **2b-primary family (Holm, 7 tests):** rejected: {', '.join(rej) if rej else 'none'}; not rejected: "
      f"{', '.join(k for k in prim if k not in rej) or 'none'} (section 5).")
    w("")
    # ------------------------------------------------------------------ 1 definitions
    w("## 1. Data and definitions")
    w("")
    w("**Teams** (plan section 0). Utterance = one rally clip (TV, `text_corrected`), one live-text update (Cornell), one player answer (press).")
    w("")
    rows = []
    for t, d in teams.items():
        rows.append([lab(t), d["medium"], d["utterances"], f"{d['tokens']:,}"])
    w(table(["team", "medium", "utterances", "tokens"], rows))
    w("")
    w("**Tokens.** Phase 2 tokeniser and STOP list (`analysis/formulas/common.py`, unchanged). **2b normalisation** (primary): digit strings and "
      "`love fifteen thirty forty deuce` -> `<num>`; first names and surnames of the players of the 20 TV matches (Phase 2 lexicon), plus the players of a Cornell update "
      "and the interviewee of a press answer -> `<name>`. Raw Phase 2 tokens are a sensitivity.")
    w("")
    w("**Formula of a team** = n-gram (2 <= n <= 12) in >= 2 distinct utterances of the team's text, not made only of STOP words; variants n >= 3 and "
      "'content' (not made only of STOP words and numerals). **Coverage** of a text by an inventory = share of its tokens inside an occurrence of an inventory n-gram. "
      "**Matched size**: each team subsampled to S = 1,500 tokens (primary; all 20 TV streams) or 3,000 (17 TV streams), whole utterances in random order, "
      "R = 500 / 200 replicates. **Null (a)**: each subsample's tokens permuted over its positions (lexicon, topic and utterance lengths kept, multiword units destroyed), "
      "identification and coverage repeated. **Excess** = observed minus shuffled coverage, per pair averaged over replicates. "
      "**Vertex bootstrap**: the 20 TV streams resampled with replacement, the statistic averaged over ordered pairs of distinct original streams; it represents "
      "the sampling of broadcasts (each pair's replicate mean held fixed).")
    w("")
    w("**Situational slot classifier** (plan section 5; code `lib2b.SlotClassifier`): (1) OFFICIAL if the span touches an umpire/Hawk-Eye pattern "
      "(`mr <name>`, `... is challenging`, `challenges remaining`, `ball was called`, `new balls please`, `thank you (players|please)`, `quiet please`, "
      "`time violation`, `hawk eye`, ...); (2) SCORE if it touches a score pattern (`<score> <score|all>`, `deuce`, `advantage <name>`, `game <name>`, "
      "`<name> leads by N games to M`, `N games all`, `break/set/match point`, `tie break`); (3) otherwise the slot whose keyword lexicon has most hits in the span "
      "(ties: OFFICIAL > SCORE > CROWD > STAT > SHOT > JUDGE); (4) the same on a window of 4 tokens either side; (5) OTHER. Overlapping lexicon entries count "
      "separately (`first serve` adds a SHOT hit to `serve`). The lexicons are frozen in the plan and were not tuned on any 2b output.")
    w("")
    w(f"**Available time.** `t_to_next_first_hit_s` is invalid in {n_fps_bad} of the 20 streams (videos at about 29.97 frames per second whose clip times "
      "were computed as frames/25, so clip and hit clocks diverge; values down to about -1,860 s), and `dead_time_before_s` exists only for the two finals. "
      "2b therefore uses the hit clock: **A_after** = first hit of the next clip minus last hit of this clip (the clip's text runs into the following dead time). "
      "This corpus defect affects any earlier use of `t_to_next_first_hit_s` in those six pool streams (none in Phase 2's tests, which used the two finals).")
    w("")
    # ------------------------------------------------------------------ 2 sharing
    w("## 2. Shared stock versus idiolect (2b.1)")
    w("")
    w("**Table 2.1. Inventory sizes** (formula types; full texts, and mean over replicates at matched size; 2b normalisation). "
      "The press corpus (5.4 million tokens) is not indexed whole.")
    w("")
    fullm = {r["team"]: r for r in inv_full if r["tokens"] == "norm"}
    mm = {(r["team"], r["S"]): r for r in inv_m if r["tokens"] == "norm"}
    rows = []
    for t in list(teams):
        fr = fullm.get(t)
        m15 = mm.get((t, "1500"))
        m30 = mm.get((t, "3000"))
        rows.append([lab(t), fr["types_n2"] if fr else "-", fr["types_n3"] if fr else "-", num(fr["types_n2_per_1000_tokens"], 1) if fr else "-",
                     num(m15["types_base"], 0) if m15 else "-", num(m15["types_n3"], 0) if m15 else "-",
                     num(m15["types_base_shuffled"], 0) if m15 else "-", num(m30["types_base"], 0) if m30 else "-"])
    w(table(["team", "full: n>=2", "full: n>=3", "full: n>=2 per 1,000 tokens", "1,500: n>=2", "1,500: n>=3", "1,500: n>=2 shuffled", "3,000: n>=2"], rows))
    w("")
    w("**Table 2.2. Coverage of TV targets by each kind of source, and of the baselines by TV sources** (% of the target's tokens; mean over pairs; "
      "95% CI from the bootstrap over TV streams). Excess = observed - shuffled.")
    w("")
    rows = []
    for Sv in ("1500", "3000"):
        for m, mlab in (("cov_base", "n >= 2"), ("cov_n3", "n >= 3"), ("cov_content", "content n >= 2")):
            for st, slab in (("TV->TV mean", "TV -> TV"), ("cornell->TV mean", "Cornell -> TV"), ("press_pooled->TV mean", "press -> TV"),
                             ("TV->cornell mean", "TV -> Cornell"), ("TV->press_pooled mean", "TV -> press")):
                o, n_, e = (a(Sv, m, f"{st} {x}") for x in ("obs", "null", "excess"))
                rows.append([Sv, mlab, slab, f"{pc(o['estimate'], 2)} {ci(o['ci_lo'], o['ci_hi'], 2)}", pc(n_["estimate"], 2),
                             f"{pc(e['estimate'], 2)} {ci(e['ci_lo'], e['ci_hi'], 2)}"])
    w(table(["S", "inventory", "source -> target", "observed", "shuffled", "excess"], rows))
    w("")
    w("**Table 2.3. TV sources minus baseline sources** (excess coverage of TV targets, pp; vertex bootstrap 95% CI). The n >= 2 rows at S = 1,500 are H2a and H2b.")
    w("")
    rows = []
    for Sv in ("1500", "3000"):
        for m, mlab in (("cov_base", "n >= 2"), ("cov_n3", "n >= 3"), ("cov_content", "content n >= 2")):
            for b, blab in (("cornell", "Cornell"), ("press_pooled", "press")):
                r = a(Sv, m, f"TV->TV minus {b}->TV excess")
                rows.append([Sv, mlab, blab, f"{pc(r['estimate'], 2)} {ci(r['ci_lo'], r['ci_hi'], 2)}"])
    w(table(["S", "inventory", "baseline", "TV minus baseline"], rows))
    w("")
    w("**Table 2.4. Jaccard overlap of inventories** (mean over pairs, %; observed, shuffled, excess).")
    w("")
    rows = []
    for Sv in ("1500", "3000"):
        for m, mlab in (("jac_base", "n >= 2"), ("jac_n3", "n >= 3")):
            for st, slab in (("TV->TV mean", "TV - TV"), ("cornell->TV mean", "Cornell - TV"), ("press_pooled->TV mean", "press - TV")):
                o, n_, e = (a(Sv, m, f"{st} {x}") for x in ("obs", "null", "excess"))
                rows.append([Sv, mlab, slab, f"{pc(o['estimate'], 2)} {ci(o['ci_lo'], o['ci_hi'], 2)}", pc(n_["estimate"], 2), pc(e["estimate"], 2)])
    w(table(["S", "inventory", "pair type", "observed", "shuffled", "excess"], rows))
    w("")
    w("'-' = undefined (both shuffled inventories empty). The shuffled Cornell texts keep a large inventory of chance bigrams (its vocabulary is concentrated), so Cornell's Jaccard excess is negative while its "
      "coverage excess is positive; coverage, not Jaccard, carries the tests.")
    w("")
    w("**Table 2.5. Raw-token sensitivity** (no `<num>`/`<name>` normalisation; S = 1,500).")
    w("")
    rows = []
    for m, mlab in (("cov_base", "n >= 2"), ("cov_n3", "n >= 3")):
        for st, slab in (("TV->TV mean", "TV -> TV"), ("cornell->TV mean", "Cornell -> TV"), ("press_pooled->TV mean", "press -> TV")):
            o, e = a(1500, m, f"{st} obs", "raw"), a(1500, m, f"{st} excess", "raw")
            rows.append([mlab, slab, f"{pc(o['estimate'], 2)} {ci(o['ci_lo'], o['ci_hi'], 2)}", f"{pc(e['estimate'], 2)} {ci(e['ci_lo'], e['ci_hi'], 2)}"])
        for b in ("cornell", "press_pooled"):
            r = a(1500, m, f"TV->TV minus {b}->TV excess", "raw")
            rows.append([mlab, f"TV minus {lab(b)}", "", f"{pc(r['estimate'], 2)} {ci(r['ci_lo'], r['ci_hi'], 2)}"])
    w(table(["inventory", "comparison", "observed", "excess"], rows))
    w("")
    w("**Table 2.6. Single-speaker press baselines** (S = 1,500, n >= 2; coverage of one interviewee's answers by another's inventory, observed / excess, %). "
      "Four speakers of one non-commentary genre, as a yardstick for cross-team sharing among TV streams.")
    w("")
    sp = ["press_federer", "press_djokovic", "press_murray", "press_nadal"]
    rows = []
    for x in sp:
        row = [lab(x)]
        for y in sp:
            if x == y:
                row.append("-")
            else:
                o = A.get(("1500", "norm", "cov_base", f"{x}->{y} obs"))
                e = A.get(("1500", "norm", "cov_base", f"{x}->{y} excess"))
                row.append(f"{pc(o['estimate'], 1)} / {pc(e['estimate'], 1)}" if o and e else "-")
        rows.append(row)
    w(table(["source \\ target"] + [lab(y) for y in sp], rows))
    w("")
    sp_ex = [f(A[("1500", "norm", "cov_base", f"{x}->{y} excess")]["estimate"]) for x in sp for y in sp if x != y]
    w(f"Mean excess between press speakers: {100 * np.mean(sp_ex):.2f} pp, against {pc(h1a['estimate'], 2)} pp between TV teams. The yardstick is not matched: "
      "a speaker's 1,500 tokens are drawn from answers given over many years and press conferences (topic-diverse, so their repeats are generic), the texts are "
      "edited transcripts without ASR errors, while a TV team's 1,500 tokens come from one match in raw ASR. Cross-team sharing among TV streams is therefore not "
      "shown to be unusually high or low for a genre.")
    w("")
    w("**Table 2.7. Each TV stream as target and as source** (S = 1,500, n >= 2, 2b normalisation; % ; mean over the other 19 TV streams).")
    w("")
    pairs = L.read_csv(R / "sharing_pairs.csv")
    P = {(r["source"], r["target"]): r for r in pairs if r["S"] == "1500" and r["tokens"] == "norm" and r["measure"] == "cov_base"}
    rows = []
    for t in L.TV:
        others = [s for s in L.TV if s != t]
        rows.append([lab(t), f"{teams[t]['tokens']:,}", pc(np.mean([f(P[(s, t)]["obs_mean"]) for s in others]), 2),
                     pc(np.mean([f(P[(s, t)]["excess"]) for s in others]), 2), pc(np.mean([f(P[(t, s)]["excess"]) for s in others]), 2),
                     pc(P[("cornell", t)]["excess"], 2), pc(P[("press_pooled", t)]["excess"], 2)])
    w(table(["stream", "tokens", "as target: observed", "as target: excess", "as source: excess", "Cornell -> it: excess", "press -> it: excess"], rows))
    w("")
    # ---- core
    w("### 2.1 Genre core")
    w("")
    w("**Table 2.8. Core size**: formula types in the inventories of at least k of the 20 TV streams (full texts; and mean over 200 subsamples of 1,500 tokens).")
    w("")
    rows = []
    for k in range(2, 21):
        fr = next(r for r in core if r["size"] == "full" and r["tokens"] == "norm" and r["k"] == str(k))
        rr = next(r for r in core if r["size"] == "full" and r["tokens"] == "raw" and r["k"] == str(k))
        mr = next(r for r in core if r["size"].startswith("matched") and r["k"] == str(k))
        rows.append([k, fr["types_base"], fr["types_n3"], fr["types_content"], rr["types_base"], num(mr["types_base"], 1), num(mr["types_n3"], 1)])
    w(table(["k", "full: n>=2", "full: n>=3", "full: content", "full raw: n>=2", "1,500: n>=2", "1,500: n>=3"], rows))
    w("")
    w("**Table 2.9. The most widely shared formulas** (full texts; K = number of streams whose inventory contains it; modal slot over its occurrences).")
    w("")
    w(table(["formula", "n", "K", "utterances (all streams)", "modal slot", "share"],
            [[f"`{r['formula']}`", r["n"], r["streams_K"], r["utterances_all_streams"], r["modal_slot"], pc(r["modal_slot_share"], 0) + "%"] for r in ctop[:40]]))
    w("")
    w("**Table 2.10. Is the TV core shared with the baselines?** Share of the core's types (full texts) that are formulas of a Cornell or press random sample "
      f"of {tv_tokens:,} tokens (the size of the 20 TV streams together; mean [2.5-97.5%] over 20 samples).")
    w("")
    w(table(["k", "core types", "in Cornell inventory", "in press inventory", "n>=3 core types", "n>=3 in Cornell", "n>=3 in press"],
            [[r["k"], r["core_types"], f"{pc(r['share_in_baseline_inventory'])} {ci(r['lo'], r['hi'])}",
              f"{pc(p['share_in_baseline_inventory'])} {ci(p['lo'], p['hi'])}", r["core_types_n3"], pc(r["share_n3_in_baseline_inventory"]),
              pc(p["share_n3_in_baseline_inventory"])]
             for r, p in zip([x for x in cbase if x["baseline"] == "cornell"], [x for x in cbase if x["baseline"] == "press_pooled"])]))
    w("")
    w("**Table 2.11. Idiolect and core shares by situational slot** (share of formula tokens; mean over the 20 streams, with min-max; 1,500-token subsamples, "
      "mean of 200; full texts in the last two columns).")
    w("")
    rows = []
    for sl in ("SCORE", "OFFICIAL", "SHOT", "JUDGE", "STAT", "CROWD", "OTHER", "ALL"):
        mv = [r for r in idio if r["size"].startswith("matched") and r["slot"] == sl]
        fv = [r for r in idio if r["size"] == "full" and r["slot"] == sl]
        idv = [f(r["share_idiolect"]) for r in mv]
        c10 = [f(r["share_core10"]) for r in mv]
        rows.append([sl, num(np.mean([f(r["formula_tokens"]) for r in mv]), 0), f"{pc(np.mean(idv))} ({pc(min(idv))}-{pc(max(idv))})",
                     pc(np.mean([f(r["share_core2"]) for r in mv])), f"{pc(np.mean(c10))} ({pc(min(c10))}-{pc(max(c10))})",
                     pc(np.mean([f(r["share_idiolect"]) for r in fv])), pc(np.mean([f(r["share_core10"]) for r in fv]))])
    w(table(["slot", "formula tokens per stream (1,500)", "idiolect % (range)", "in >= 2 streams %", "core-10 % (range)", "full: idiolect %", "full: core-10 %"], rows))
    w("")
    sm = core_meta["spearman_idiolect_vs_stream_tokens"]
    w(f"Idiolect share against stream length: Spearman rho = {num(sm['full'][0], 2)} (p = {pval(sm['full'][1])}) on full texts, "
      f"{num(sm['matched'][0], 2)} (p = {pval(sm['matched'][1])}) at 1,500 tokens. Full-text shares depend on how many other long streams exist; matched-size shares on "
      "how much of a stream one sample contains. Neither is a pure team property.")
    w("")
    w("**Table 2.12. Idiolect share per stream** (all slots).")
    w("")
    rows = []
    for t in L.TV:
        mr = next(r for r in idio if r["size"].startswith("matched") and r["slot"] == "ALL" and r["stream"] == t)
        fr = next(r for r in idio if r["size"] == "full" and r["slot"] == "ALL" and r["stream"] == t)
        rows.append([lab(t), f"{teams[t]['tokens']:,}", f"{pc(mr['share_idiolect'])} {ci(mr['share_idiolect_lo'], mr['share_idiolect_hi'])}",
                     pc(mr["share_core10"]), pc(fr["share_idiolect"]), pc(fr["share_core10"])])
    w(table(["stream", "tokens", "1,500: idiolect % [2.5-97.5% over subsamples]", "1,500: core-10 %", "full: idiolect %", "full: core-10 %"], rows))
    w("")
    # ---- clusters
    w("### 2.2 Clusters (exploratory)")
    w("")
    w("Pair similarity = symmetric excess coverage (n >= 2, S = 1,500) or observed Jaccard. Within-minus-between = mean similarity of pairs sharing the label minus "
      "the mean of the other pairs; null = labels permuted over the 20 streams (10,000 permutations; the hint cluster enumerated exactly). Mantel rows give the "
      "correlation with the pair covariate (node permutation). One-sided p in the direction 'more sharing'.")
    w("")
    w(table(["similarity", "label", "pairs within", "within - between (or r)", "null 95%", "p"],
            [[r["similarity"], r["label"], r["within_pairs"], num(r["within_minus_between"], 4), ci(r["null_lo"], r["null_hi"], 4, 1), pval(r["p_one_sided_higher_within"])]
             for r in clus]))
    w("")
    w("**Table 2.13. QAP regression of pair similarity** on same slam, same gender, shared players, |year difference| and same hint (node-permutation p, two-sided; "
      "the intercept's p is not meaningful).")
    w("")
    w(table(["similarity", "term", "beta", "p"], [[r["similarity"], r["term"], num(r["beta"], 4), pval(r["p_two_sided_node_permutation"])] for r in qap]))
    w("")
    pe = pair["excess_cov_sym"]
    w(f"The 2019-2023 pair (both Wimbledon men's finals with Djokovic; hint 'Tim' in both): symmetric excess {pc(pe['value'], 2)} pp, rank {pe['rank_among_190_pairs']} "
      f"of {pe['n_pairs']} (mean of all pairs {pc(pe['mean_all_pairs'], 2)}); Jaccard rank {pair['jaccard_obs']['rank_among_190_pairs']}. The most similar pairs are "
      + "; ".join(f"{x} / {y} ({pc(v, 2)})" for x, y, v in pe["top5_pairs"][:3]) + ", i.e. Roland Garros women's finals with Swiatek "
      "(same slam, same gender, same player, and probably the same host broadcaster).")
    w("")
    # ---- pool to target
    w("### 2.3 Pool -> target coverage for every stream (exploratory, for the record)")
    w("")
    w("I = the other 19 TV streams pooled (raw Phase 2 tokens and 2b normalisation), M = the stream; 95% bootstrap CI over M's utterances (I fixed). "
      "Matched I = random 100,000-token subsamples of the other 19 streams (mean and range over 20).")
    w("")
    rows = []
    for t in L.TV:
        g = {(r["mode"], r["tokens"]): r for r in p2t if r["target"] == t}
        rr, nn = g[("loo19", "raw")], g[("loo19", "norm")]
        mt = next(r for r in p2t if r["target"] == t and r["mode"].startswith("matched"))
        rows.append([lab(t), f"{pc(rr['base'])} {ci(rr['base_lo'], rr['base_hi'])}", f"{pc(rr['n3'])} {ci(rr['n3_lo'], rr['n3_hi'])}",
                     f"{pc(nn['base'])}", f"{pc(mt['base'])} {ci(mt['base_lo'], mt['base_hi'])}", pc(mt["n3"])])
    w(table(["target", "raw n>=2", "raw n>=3", "2b-normalised n>=2", "matched I: n>=2 [range]", "matched I: n>=3"], rows))
    w("")
    w(f"2019 ranks {p2t_meta['rank_2019_loo19_raw_base']} of {p2t_meta['n_targets']} (matched I: {p2t_meta['rank_2019_matched_raw_base']}). With the Phase 2 "
      f"identification set (18 pool streams) the 2019 value is {pc(p2t_meta['check_phase2_pool18_2019_raw_base'], 2)}%, equal to Phase 2's.")
    w("")
    # ------------------------------------------------------------------ 3 calibration
    w("## 3. Calibration against Parry's definition (2b.2)")
    w("")
    w("Two coders marked formula spans in a fixed sample of 300 utterances (150 from the 2019 final, 150 from the other 19 streams in proportion to their length; "
      "`sample_ids.json`) following `manual.md`, blind to the automatic inventory. **Both coders are LLM agents, not human specialists**: their agreement measures "
      "the reliability of two runs of the same kind of judge, and precision/recall against them measures agreement with that judge, not validity against Parry's concept.")
    w("")
    if cal_ok:
        ca = L.read_json(R / "calibration_agreement.json")
        cm = L.read_json(R / "calibration_meta.json")
        fs = ca["file_stats"]
        w(f"Utterances coded by both: {ca['utterances_both']} ({ca['tokens']:,} tokens). Spans in the files: A {fs['A'].get('spans_in_file', 0)}, "
          f"B {fs['B'].get('spans_in_file', 0)}; re-located because `text` did not equal the slice: A {fs['A'].get('relocated', 0)}, B {fs['B'].get('relocated', 0)}; "
          f"dropped: A {fs['A'].get('dropped_not_found', 0) + fs['A'].get('dropped_no_token', 0)}, B {fs['B'].get('dropped_not_found', 0) + fs['B'].get('dropped_no_token', 0)}.")
        w("")
        w("**Table 3.1. Inter-coder agreement** (bootstrap over utterances, B = 2,000).")
        w("")
        rows = []
        for key, labk in (("primary_HIGH_MEDIUM", "HIGH + MEDIUM spans (primary)"), ("all_confidences", "all spans incl. LOW")):
            x = ca[key]
            rows.append([labk, f"{num(x['token_kappa'], 3)} {ci(x['token_kappa_ci'][0], x['token_kappa_ci'][1], 3, 1)}",
                         f"{pc(x['positive_token_share_A'])} / {pc(x['positive_token_share_B'])}", f"{x['spans_A']} / {x['spans_B']}",
                         f"{num(x['span_F1_exact'], 3)} {ci(x['span_F1_exact_ci'][0], x['span_F1_exact_ci'][1], 3, 1)}",
                         f"{num(x['span_F1_overlap'], 3)} {ci(x['span_F1_overlap_ci'][0], x['span_F1_overlap_ci'][1], 3, 1)}", x["matched_spans"],
                         f"{pc(x['slot_agreement'])} (kappa {num(x['slot_kappa'], 2)})", f"{pc(x['type_agreement'])} (kappa {num(x['type_kappa'], 2)})"])
        w(table(["span set", "token kappa", "tokens positive A / B %", "spans A / B", "span F1 exact", "span F1 overlap", "matched spans",
                 "slot agreement %", "type agreement %"], rows))
        w("")
        sc = ca["span_counts"]
        w("Span counts by slot: A " + ", ".join(f"{k} {v}" for k, v in sorted(sc["A"]["by_slot"].items())) + "; B "
          + ", ".join(f"{k} {v}" for k, v in sorted(sc["B"]["by_slot"].items())) + ". By confidence: A "
          + ", ".join(f"{k} {v}" for k, v in sorted(sc["A"]["by_confidence"].items())) + "; B "
          + ", ".join(f"{k} {v}" for k, v in sorted(sc["B"]["by_confidence"].items())) + ".")
        w("")
        w("**Table 3.2. Automatic measures against the coders** (token level, HIGH + MEDIUM spans; precision / recall / F1 with bootstrap 95% CI over utterances). "
          "'Pool' = the 18 pool streams minus the utterance's own; 'in-sample' = the utterance's own stream. Rows marked exploratory were added in the plan beyond the brief.")
        w("")
        prows = L.read_csv(R / "calibration_prf.csv")
        rows = []
        for r in prows:
            if r["coder_confidence"] != "HIGH+MEDIUM":
                continue
            rows.append([r["label"], r["reference"].replace("_", " "), pc(r["auto_positive_share"]),
                         f"{num(r['precision'], 2)} {ci(r['precision_lo'], r['precision_hi'], 2, 1)}", f"{num(r['recall'], 2)} {ci(r['recall_lo'], r['recall_hi'], 2, 1)}",
                         f"{num(r['F1'], 2)} {ci(r['F1_lo'], r['F1_hi'], 2, 1)}"])
        w(table(["automatic measure", "reference", "auto-positive tokens %", "precision", "recall", "F1"], rows))
        w("")
        w("**Table 3.3. Strata** (pool n >= 2 and pool n >= 3 against each coder): recall by the coder's slot and by span confidence; precision by the classifier's "
          "token slot; and P / R / F1 by sample group.")
        w("")
        st = L.read_csv(R / "calibration_strata.csv")
        rows = [[r["measure"], r["reference"], r["stratum_kind"], r["stratum"], r["numerator"], r["denominator"],
                 r["value"] if "/" in r["value"] else num(r["value"], 3)] for r in st if r["measure"] in ("pool_n2", "pool_n3")]
        w(table(["measure", "coder", "kind", "stratum", "numerator", "denominator", "value"], rows))
        w("")
        def strat(meas, kind):
            vals = defaultdict(list)
            for r in st:
                if r["measure"] == meas and r["stratum_kind"] == kind:
                    vals[r["stratum"]].append(f(r["value"]))
            return {k: (min(v), max(v)) for k, v in vals.items()}
        rs_ = strat("pool_n2", "recall by coder slot")
        ps_ = strat("pool_n2", "precision by classifier slot")
        def rng_(d, k):
            return f"{num(d[k][0], 2)}-{num(d[k][1], 2)}" if k in d else "-"
        hi_r = sorted(rs_, key=lambda k: -rs_[k][0])[:2]
        lo_r = sorted(rs_, key=lambda k: rs_[k][0])[:2]
        hi_p = sorted(ps_, key=lambda k: -ps_[k][0])[:2]
        lo_p = sorted(ps_, key=lambda k: ps_[k][0])[:2]
        g19 = [r for r in st if r["measure"] == "pool_n2" and r["stratum_kind"].startswith("precision / recall") and r["stratum"] == "2019"]
        goth = [r for r in st if r["measure"] == "pool_n2" and r["stratum_kind"].startswith("precision / recall") and r["stratum"] == "other"]
        w("**Reading.** The pool n >= 2 measure (Phase 2's) marks "
          f"{pc(next(r for r in prows if r['measure'] == 'pool_n2')['auto_positive_share'], 0)}% of tokens, the coders "
          f"{pc(ca['primary_HIGH_MEDIUM']['positive_token_share_B'], 0)}-{pc(ca['primary_HIGH_MEDIUM']['positive_token_share_A'], 0)}%. Its recall (range over the two "
          f"coders) is highest for " + ", ".join(f"{k} ({rng_(rs_, k)})" for k in hi_r) + " spans and lowest for " + ", ".join(f"{k} ({rng_(rs_, k)})" for k in lo_r)
          + "; its precision is highest where the classifier places a token in " + ", ".join(f"{k} ({rng_(ps_, k)})" for k in hi_p) + " and lowest in "
          + ", ".join(f"{k} ({rng_(ps_, k)})" for k in lo_p) + ". Precision is higher on the 2019 utterances than on the other streams' ("
          + " vs ".join(x[0]["value"].split(" / ")[0] if x else "-" for x in (g19[:1], goth[:1])) + " for coder A). The repetition statistic thus recovers the "
          "score-call and umpire formulas that the coders also recognise, and over-counts ordinary collocations in evaluative and other talk; no automatic variant "
          "reaches a precision above about 0.45 against either coder.")
        w("")
        w("**Table 3.4. Slot classifier against the coders' slot labels** (every coder span; rows = coder, columns = classifier).")
        w("")
        cl = L.read_csv(R / "calibration_slot_classifier.csv")
        for who in ("A", "B"):
            M = defaultdict(Counter)
            for r in cl:
                if r["coder"] == who:
                    M[r["coder_slot"]][r["classifier_slot"]] += int(r["spans"])
            cols = list(L.SLOTS)
            rows = [[c] + [M[c].get(k, 0) for k in cols] + [sum(M[c].values())] for c in sorted(M)]
            v = cm["classifier_vs_coder"][who]
            w(f"Coder {who}: agreement {pc(v['agreement'])}%, kappa {num(v['kappa'], 3)} ({v['spans']} spans).")
            w("")
            w(table([f"coder {who} \\ classifier"] + cols + ["total"], rows))
            w("")
    else:
        st = L.read_json(R / "calibration_status.json") if (R / "calibration_status.json").exists() else {"status": "not run"}
        w(f"Status: {st['status']}. `calibrate.py` is tested on a synthetic example (`tests/test_calibrate.py`) and runs from `run_all.sh` once both files exist.")
        w("")
    # ------------------------------------------------------------------ 4 thrift
    w("## 4. Thrift and extension per situational slot (2b.3)")
    w("")
    w(f"Referring expressions were extracted for the two players of every TV stream ({rsum['n_references']} references; {rsum['n_umpire_pattern']} inside umpire "
      f"patterns; {rsum['n_unresolved_epithets']} descriptive epithets without a resolved referent). The extraction reproduces Phase 2's totals for the two finals "
      f"({', '.join(f'{k}: ' + ', '.join(f'{p} {n}' for p, n in sorted(v.items())) for k, v in rsum['check_phase2_totals_all_references'].items())}).")
    w("")
    w("**Table 4.1. How each team names the players** (commentary-only resolved references; shares %; epithet upper bound counts every unresolved epithet as a player reference).")
    w("")
    rows = []
    for r in cats:
        if r["references"] != "commentary_only":
            continue
        rows.append([r["label"], r["resolved_tokens"], pc(r["share_surname"], 0), pc(r["share_first_name"], 0), pc(r["share_full_name"], 0),
                     pc(r["share_hypocoristic"], 0), pc(r["share_epithet"], 0), pc(r["share_epithet_upper"], 0)])
    w(table(["team", "references", "surname", "first name", "full name", "hypocoristic", "epithet", "epithet (upper)"], rows))
    w("")
    w("**Table 4.2. Economy of naming by situational slot** (commentary-only references, all teams; per team x player x slot cell: modal-form share and distinct "
      "forms per 100 references, averaged over cells with >= 5 references; distinct forms per 100 tokens of the slot, averaged over cells).")
    w("")
    rows = []
    for sl in L.SLOTS:
        cells = [r for r in econ if r["slot_type"] == "situational" and r["slot"] == sl]
        big = [r for r in cells if int(r["references"]) >= 5]
        rows.append([sl, sum(int(r["references"]) for r in cells), len(cells), len(big),
                     pc(np.mean([f(r["modal_share"]) for r in big])) if big else "-", num(np.mean([f(r["distinct_per_100_refs"]) for r in big]), 1) if big else "-",
                     num(np.mean([f(r["distinct_per_100_slot_tokens"]) for r in cells if r["distinct_per_100_slot_tokens"]]), 2)])
    w(table(["slot", "references", "cells", "cells >= 5", "modal share %", "distinct per 100 refs", "distinct per 100 slot tokens"], rows))
    w("")
    w("**Table 4.3. One form per slot?** (cells = player x slot with >= 5 commentary references; criterion in plan section 9).")
    w("")
    def team_econ(t, st):
        cs = [r for r in econ if r["team"] == t and r["slot_type"] == st and int(r["references"]) >= 5]
        return (num(np.mean([f(r["modal_share"]) for r in cs]), 2), num(np.mean([f(r["distinct_per_100_refs"]) for r in cs]), 1)) if cs else ("-", "-")
    w(table(["team", "slot type", "cells >= 5", "mean modal share", "distinct forms per 100 refs", "cells with modal share >= 0.9", "lowest modal share", "verdict"],
            [[r["label"], r["slot_type"], r["cells_ge5"], *team_econ(r["team"], r["slot_type"]), r["cells_modal_ge_0.9"], num(r["min_modal_share"], 2),
              r["verdict"]] for r in parr]))
    w("")
    w("**Table 4.4. Thrift tests** (D = sum over cells of distinct categories (H4a) or forms (H4b); one-sided p for fewer than under the null).")
    w("")
    w(table(["test", "references", "slot type", "team", "tokens", "D", "null mean", "null 95%", "p", "status"],
            [[r["test"], r["references"], r["slot_type"], r.get("team", ""), r["tokens"], r["D_obs"], num(r["null_mean"], 1),
              f"[{r['null_lo']}, {r['null_hi']}]" if r.get("null_lo") else "", pval(r["p_one_sided_fewer"]), r["status"]] for r in thr]))
    w("")
    w("**Table 4.5. Power of H4b** (simulation: with probability theta a reference takes a designated form of its team x player x slot cell; "
      f"{mde[0]['simulations']} data sets per theta, {mde[0]['permutations']} permutations each).")
    w("")
    w(table(["theta", "power at alpha 0.05"], [[r["theta"], num(r["power_at_0.05"], 3)] for r in mde]))
    w("")
    w("**Table 4.5b. POST HOC: H4 with de-clustered references, and the contribution of each slot to H4b** (one reference per player per utterance; "
      "slot rows: distinct forms observed vs the mean under the H4b permutation, all commentary-only references).")
    w("")
    w(table(["test", "token set", "tokens", "D", "null mean", "null 95%", "p (fewer)"],
            [[r["test"], r["token_set"], r["tokens"], r["D_obs"], num(r["null_mean"], 1), f"[{num(r['null_lo'], 0)}, {num(r['null_hi'], 0)}]",
              pval(r["p_one_sided_fewer"])] for r in h4d]))
    w("")
    w(table(["slot", "references", "distinct forms (sum over team x player)", "null mean", "observed - null", "null 95%"],
            [[r["slot"], r["references"], num(r["distinct_obs"], 0), num(r["null_mean"], 1), num(r["obs_minus_null"], 1),
              f"[{num(r['null_lo'], 0)}, {num(r['null_hi'], 0)}]"] for r in h4s]))
    w("")
    w("**Table 4.6. Extension: syllables vs available time** (weighted mean of within-stream Spearman rho; permutation of the time values among utterances within stream; "
      "MDE = 2.80 x the null SD, normal approximation).")
    w("")
    w(table(["analysis", "references", "time", "tokens", "streams", "rho", "stream bootstrap 95%", "null 95%", "p (two-sided)", "MDE rho", "status"],
            [[r["analysis"], r["references"], r["time"], r["tokens"], r["streams"], num(r["rho_weighted"], 3), ci(r["boot_lo"], r["boot_hi"], 3, 1),
              ci(r["null_lo"], r["null_hi"], 3, 1), pval(r["p_two"]), num(r["mde_rho_approx"], 3), r["status"]] for r in ext]))
    w("")
    ml = h5.get("mixedlm", {})
    if "coef_logA" in ml:
        w(f"Mixed model ({ml['model']}; {ml['tokens']} references, {ml['groups']} streams; exploratory): coefficient of log A_after = {num(ml['coef_logA'], 3)} "
          f"syllables per log-second [{num(ml['ci_lo'], 3)}, {num(ml['ci_hi'], 3)}], p = {pval(ml['p'])}.")
        w("")
    # ---- E1
    w("### 4.1 Formula expressions per slot (E1, exploratory)")
    w("")
    em = tmeta["e1"]
    w(f"Genre inventory identified on the 20 TV streams pooled: {em['genre_formulas']:,} formulas and {em['genre_open_systems']:,} open-slot systems; greedy "
      f"longest-first segmentation gives {em['occurrences']:,} occurrences. Per stream x slot: occurrences, distinct types per 100 tokens of the slot and modal-type share; "
      "null: team labels permuted among the slot's occurrences (10,000 permutations).")
    w("")
    rows = []
    for r in e1t:
        sl = r["slot"]
        cells = [x for x in e1 if x["slot"] == sl]
        rows.append([sl, r["occurrences"], num(np.mean([f(x["distinct_per_100_slot_tokens"]) for x in cells if x["distinct_per_100_slot_tokens"]]), 1),
                     r["D_obs"], num(r["null_mean"], 1), pval(r["p_one_sided_fewer"]),
                     pc(r["modal_share_obs"]), pc(r["modal_share_null_mean"]), pval(r["p_one_sided_modal_higher"])])
    w("**Table 4.7. E1 economy and across-team null by slot.**")
    w("")
    w(table(["slot", "occurrences", "distinct types per 100 slot tokens (mean over teams)", "D (sum over teams of distinct types)", "null D",
             "p (fewer)", "modal-type share % (mean over teams)", "null", "p (higher)"], rows))
    w("")
    w("Commonest types per slot (all teams): " + "; ".join(
        f"{sl}: " + ", ".join([f"`{r['type']}` {pc(r['share_of_slot_occurrences'], 1)}% ({r['teams_using']} teams)" for r in e1top if r["slot"] == sl][:4])
        for sl in L.SLOTS if any(r["slot"] == sl for r in e1top)) + ".")
    w("")
    w("Every slot shows fewer distinct types per team than if occurrences were dealt to teams at random: each stream reuses its own formula types. "
      "Because a stream is one match, this is stream-specific repetition (team and match topic together; e.g. `the wind predictor`, `in the box`), not "
      "evidence of a team idiolect independent of the match.")
    w("")
    w("**Table 4.8. Economy per team and slot (E1)**: distinct formula types per 100 tokens of the slot / modal-type share %.")
    w("")
    rows = []
    for t in L.TV:
        row = [lab(t)]
        for sl in L.SLOTS:
            x = next((r for r in e1 if r["team"] == t and r["slot"] == sl), None)
            row.append(f"{num(x['distinct_per_100_slot_tokens'], 1)} / {pc(x['modal_share'], 0)}" if x and x["occurrences"] != "0" else "-")
        rows.append(row)
    w(table(["team"] + list(L.SLOTS), rows))
    w("")
    w("Slot share of all tokens (token-level classifier), mean over the 20 TV streams: " + ", ".join(
        f"{sl} {pc(np.mean([f(r['share']) for r in slot_tok if r['slot'] == sl]))}%" for sl in L.SLOTS) + ".")
    w("")
    # ---- E2
    w("### 4.2 Functional-equivalence classes (E2, exploratory)")
    w("")
    w("Each class is a set of expressions declared equivalent in the plan (section 9) before counting. Forms pooled over the 20 TV teams, the Cornell and press "
      "modal forms, and the across-team null (team labels permuted among the class's TV occurrences; one-sided p for fewer distinct forms per team / higher modal share "
      "than chance, i.e. team-specific choice).")
    w("")
    rows = []
    for cname, slot, forms in __import__("p05_thrift").E2:
        tv = [r for r in e2 if r["class"] == cname and r["medium"] == "tv"]
        pooled = Counter()
        for r in tv:
            for item in (r["forms"] or "").split("; "):
                if item:
                    k, v = item.rsplit(":", 1)
                    pooled[k] += int(v)
        n = sum(pooled.values())
        corn = next(r for r in e2 if r["class"] == cname and r["team"] == "cornell")
        pres = next(r for r in e2 if r["class"] == cname and r["team"] == "press_pooled")
        t = next((x for x in e2t if x.get("class") == cname), {})
        rows.append([cname, slot, n, sum(1 for r in tv if int(r["occurrences"]) > 0),
                     ", ".join(f"{k} {100 * v / n:.0f}%" for k, v in pooled.most_common(4)) if n else "-",
                     f"{corn['modal_form']} ({pc(corn['modal_share'], 0)}%, n {corn['occurrences']})" if corn["occurrences"] != "0" else "-",
                     f"{pres['modal_form']} ({pc(pres['modal_share'], 0)}%, n {pres['occurrences']})" if pres["occurrences"] != "0" else "-",
                     f"{t.get('D_obs', '-')} / {num(t.get('null_mean'), 1)}", pval(t.get("p_one_sided_fewer")), pval(t.get("p_one_sided_modal_higher"))])
    w("**Table 4.9. Functional-equivalence classes.**")
    w("")
    w(table(["class", "slot", "TV occurrences", "TV teams using", "TV forms (pooled)", "Cornell modal form", "press modal form", "D / null D", "p (fewer)",
             "p (modal higher)"], rows))
    w("")
    # ------------------------------------------------------------------ 5 primary
    w("## 5. The seven 2b-primary tests (Holm-Bonferroni, alpha = 0.05)")
    w("")
    w("Fixed in plan section 7 before any test ran. Null hypotheses: H1, matched-size coverage of a TV stream by another TV stream's inventory equals that of their "
      "unigram-shuffled texts; H2, that excess is no larger for TV sources than for the Cornell (H2a) / press (H2b) source; H4a, given the slot, the reference category is "
      "independent of the team; H4b, within team x player, the form is independent of the situational slot; H5, within stream, a reference's syllable count is independent "
      "of the time after its clip. H1/H2 p-values are percentile-bootstrap approximations over broadcasts treated as exchangeable draws; at their floor they only say "
      "that no bootstrap draw crossed zero.")
    w("")
    w(table(["id", "claim", "estimate", "interval", "p", "kind of p", "Holm p", "rejected", "detail"],
            [[r["id"], r["claim"], num(r["estimate"], 0 if r["id"].startswith("H4") else 4), r["interval"], pval(r["p"]), r["p_kind"], pval(r["p_holm"]), r["reject_holm_0.05"], r["detail"]]
             for r in prim.values()]))
    w("")
    n_expl = (sum(1 for r in thr if r["status"] != "2b-primary") + sum(1 for r in ext if r["status"] != "2b-primary")
              + len(e1t) + sum(1 for r in e2t if r.get("D_obs")) + len(clus) + len(qap) + len(h4d))
    w(f"H4b is rejected only narrowly after Holm (p = {pval(prim['H4b']['p_holm'])}); the effect is small ({h4b['D_obs']} distinct forms against "
      f"{num(h4b['null_mean'], 1)} expected), and the slot is a keyword classification of a clip-level window (section 3, Table 3.4: about 58% agreement with "
      "the coders), so H4b shows that name forms vary a little less within some contexts than chance would give, not that commentators keep a form per metrical "
      "or situational slot. H1 and H2 are large relative to their intervals; their p-values are at the bootstrap floor.")
    w("")
    w(f"Exploratory tests reported with p-values in sections 2 and 4: {n_expl} (cluster, QAP, thrift, extension, E1 and E2 rows), unadjusted; with this many, "
      "several values below 0.05 are expected by chance.")
    w("")
    # ------------------------------------------------------------------ 6 limitations
    w("## 6. Limitations")
    w("")
    w("1. **Repetition, not Parry's formula.** Every inventory is a set of exact n-grams repeated within a text. The calibration (section 3) shows how far this agrees with "
      "LLM coders applying Parry's definition; it cannot show agreement with human specialists, and the coders' kappa is a reliability figure for two runs of one kind of judge.")
    w("2. **ASR noise.** The TV texts are raw WhisperX output with an unknown word error rate (lower bound 22 visible errors per 1,000 words, Phase 2); errors break "
      "exact repeats in both the source and the target of a TV-TV pair but only in the target of a Cornell/press-TV pair, so H1 and H2 are attenuated, and H2's "
      "positive difference is conservative in that respect. The press answers are edited stenography and Cornell is edited prose.")
    w("3. **Clip-level text and time.** A clip's text runs into the following dead time; slots are assigned to spans or windows by a keyword classifier, and "
      "A_after is a clip property. Extension and thrift tests are therefore about clip-level co-variation, not about the moment a word is chosen.")
    w("4. **Teams are not identified.** A stream is one match with one unnamed broadcaster; commentator hints exist for four streams and are [unverified]; the "
      "only two-member hint cluster coincides with same slam, same player and same round. Same-slam similarity mixes broadcaster, venue and surface vocabulary.")
    w("5. **Matched size is small.** 1,500 tokens (set by the shortest stream) gives inventories of about 70-150 types per TV stream; absolute sharing levels depend "
      "on S (compare S = 3,000) and on the subsampling scheme (random utterances from the whole match). Idiolect shares depend on stream length (section 2.1).")
    w("6. **Baselines are different corpora.** Cornell (one outlet, other matches, written) and the press answers (other genre, 2007-2015 transcripts) differ from the TV "
      "streams in matches, period, transcription and segmentation; H2 says TV sources share more bigram-level material with TV targets than these sources do, not why.")
    w("7. **Hand inputs.** The slot lexicons, the E2 equivalence classes and the demonym lists are my own specification; three nationalities (Alcaraz, Raducanu, "
      "Shelton) are entered by hand [unverified]; descriptive epithets outside the two finals are left unresolved rather than hand-assigned.")
    w(f"8. **Corpus timing defect.** `t_to_next_first_hit_s` is wrong in {n_fps_bad} streams (frame-rate mismatch); 2b uses the hit clock instead. The defect should "
      "be fixed in corpus/ (not edited here).")
    w("9. **Exploratory status.** All of 2b was designed after Phase 2's results were known; the 2b-primary family limits multiplicity within 2b but is not a "
      "pre-registration in the Phase 2 sense.")
    w("")
    # ------------------------------------------------------------------ 7 post hoc
    w("## 7. Post hoc changes (made after a first look at outputs)")
    w("")
    w(f"1. Nationality epithets: a match whose demonym modifies a following non-person noun ('the greek fans', 'the czech republic', 'the italian riviera') is not "
      f"counted as a player reference (spaCy dependency rule; {rsum['post_hoc_excluded_adjectival_nationality_matches']} matches excluded, each listed with its excerpt "
      "in `results/refexpr_pool_epithets.csv`; a few exclusions are parser errors, e.g. 'the pole powers on').")
    w(f"2. Hypocoristic + surname ('rafa nadal', 'nole djokovic') counted as one full-name reference ({rsum['post_hoc_hypocoristic_full_names']} cases), not two.")
    w("3. Added beyond the plan's text: the full-size inventory table includes Cornell but not the press corpus (too large to index whole); the E2 extension uses "
      f"{tmeta['E2_extension_permutations']} permutations (it has about 300 strata).")
    w("4. H4b power simulation corrected: the first run planted slot-specific forms on the observed data, which already carries the observed effect, so its "
      "'power' at theta = 0 was the rejection rate of the observed data (0.995); the corrected simulation starts every data set from the observed forms with slot labels "
      "permuted within team x player, so H0 holds at theta = 0 (Table 4.5 reports the corrected run).")
    w("5. Table 4.5b (H4 with one reference per player per utterance, and the per-slot contribution to D_b) was added after the H4b result was seen, to check "
      "whether clustering of references within utterances drives it (`p05b_h4_declustered.py`).")
    w("")
    # ------------------------------------------------------------------ 8 files
    w("## 8. Files")
    w("")
    w("Code: `lib2b.py`, `p00_players.py`, `p01_sharing.py`, `p02_core.py`, `p03_clusters_targets.py`, `p04_refexpr_pool.py`, `p05_thrift.py`, `calibrate.py`, "
      "`p05b_h4_declustered.py`, `p06_primary.py`, `p07_figures.py`, `make_report.py`, `run_all.sh`, `tests/`. Hand input: `hand/players.tsv`. Results: `results/*.csv|json` (runtimes in "
      "`sharing_meta.json`, `core_meta.json`, `pool_to_target_meta.json`, `thrift_meta.json`). Figures: `figures/fig1_sharing_heatmap.png` (pair matrix), "
      "`fig2_sharing_summary.png`, `fig3_core_curve.png`, `fig4_idiolect_by_slot.png`, `fig5_pool_to_target.png`, `fig6_refexpr_categories.png`, "
      "`fig7_extension.png`" + (", `fig8_calibration.png`" if cal_ok else "") + ".")
    w("")
    w("![pairwise sharing](figures/fig1_sharing_heatmap.png)")
    w("![sharing summary](figures/fig2_sharing_summary.png)")
    w("![core](figures/fig3_core_curve.png)")
    w("![idiolect by slot](figures/fig4_idiolect_by_slot.png)")
    w("![pool to target](figures/fig5_pool_to_target.png)")
    w("![naming](figures/fig6_refexpr_categories.png)")
    w("![extension](figures/fig7_extension.png)")
    if cal_ok:
        w("![calibration](figures/fig8_calibration.png)")
    OUT.write_text("\n".join(S) + "\n", encoding="utf-8")
    print("wrote", OUT, len(S), "lines")


if __name__ == "__main__":
    main()
