"""Builds analysis/formulas/report.md from results/ (every number is read from a results file).
Run: python -I analysis/formulas/make_report.py
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import csv
import json
import math
import common as C

R = C.RESULTS


def rcsv(name, delim=","):
    with open(R / name, encoding="utf-8") as fh:
        return list(csv.DictReader(fh, delimiter=delim))


def rjson(name):
    return json.loads((R / name).read_text())


def pc(x, d=1):
    return "NA" if x in (None, "", "None") else f"{100 * float(x):.{d}f}"


def ci(lo, hi, d=1):
    return f"[{pc(lo, d)}, {pc(hi, d)}]"


def f3(x):
    return f"{float(x):.3f}"


def pv(p):
    p = float(p)
    return f"{p:.4f}" if p >= 0.0001 else f"{p:.1e}"


def table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    for r in rows:
        out.append("| " + " | ".join(str(x) for x in r) + " |")
    return "\n".join(out)


def wilson(k, n, z=1.96):
    p = k / n
    den = 1 + z * z / n
    c = (p + z * z / (2 * n)) / den
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
    return c - h, c + h


def main():
    meta = rjson("density_main_meta.json")
    mmeta = rjson("density_medium_meta.json")
    fsum = rjson("formulas_summary.json")
    ssum = rjson("systems_summary.json")
    rsum = rjson("refexpr_summary.json")
    slotv = rjson("slot_validation.json")
    asr = json.loads((C.ROOT / "corpus" / "reports" / "asr_proxy.json").read_text())
    dm = rcsv("density_main.csv")
    ds = rcsv("density_sensitivity.csv")
    dctx = rcsv("density_context.csv")
    dstr = rcsv("density_streams.csv")
    dmed = rcsv("density_medium.csv")
    conf = rcsv("confirmatory.csv")
    medc = rcsv("medium_contrasts.csv")
    byn = rcsv("formulas_by_n.csv")
    mm = rcsv("maximal_match_2019.csv")
    cs = rcsv("formulas_cross_stream.csv")
    f19 = rcsv("formulas_2019.tsv", "\t")
    s19 = rcsv("systems_2019.tsv", "\t")
    sbt = rcsv("systems_by_type.csv")
    inv = rcsv("refexpr_inventory.csv")
    bys = rcsv("refexpr_by_slot.csv")
    byc = rcsv("refexpr_by_context.csv")
    syl = rcsv("refexpr_syllables.csv")
    pron = rcsv("pronouns.csv")
    th = rcsv("thrift_tests.csv")
    ext = rcsv("extension.csv")
    lt = rcsv("length_time_tests.csv")
    top = rcsv("top10_for_brief.csv")
    top3 = rcsv("top10_for_brief_n3.csv")
    c3 = rjson("c3_time_tests.json")
    kv = rcsv("../hand/kuiper_verification.tsv", "\t")

    def dmv(design, ident, meas, measure, rows=dm, variant="primary"):
        for r in rows:
            if r["design"] == design and r["identified_on"] == ident and r["measured_on"] == meas and r["measure"] == measure \
                    and r["variant"] == variant:
                return r
        raise KeyError((design, ident, meas, measure, variant))

    def medv(design, corpus, est, measure):
        for r in dmed:
            if r["design"] == design and r["corpus"] == corpus and r["estimate"] == est and r["measure"] == measure:
                return r
        raise KeyError((design, corpus, est, measure))

    def cf(i):
        return next(r for r in conf if r["id"] == i)

    T19, T23, TP = meta["tokens_2019"], meta["tokens_2023"], meta["tokens_pool"]
    d1 = dmv("D1_in_sample", C.MAIN, C.MAIN, "a")
    d1b = dmv("D1_in_sample", C.MAIN, C.MAIN, "a+b")
    d2 = dmv("D2_split_half", "2019 halves", "2019 other half (pooled)", "a")
    d2b = dmv("D2_split_half", "2019 halves", "2019 other half (pooled)", "a+b")
    d3 = dmv("D3_held_out", "pool (18 matches)", C.MAIN, "a")
    d3b = dmv("D3_held_out", "pool (18 matches)", C.MAIN, "a+b")
    d3x = dmv("D3_held_out", C.MAIN, C.HELDOUT, "a")
    d3xb = dmv("D3_held_out", C.MAIN, C.HELDOUT, "a+b")
    sh_in = dmv("D1_in_sample", "2019 shuffled words", "2019 shuffled words", "a", ds, f"D7_shuffled_word_baseline_R{meta['R_shuffle']}")
    sh_sp = dmv("D2_split_half", "2019 shuffled words", "2019 shuffled words", "a", ds, f"D7_shuffled_word_baseline_R{meta['R_shuffle']}")
    L = []
    A = L.append

    A("# Formula analysis (Phase 2): oral-formulaic measures on live tennis commentary")
    A("")
    A("Generated by `analysis/formulas/make_report.py` from `analysis/formulas/results/`; rerun everything with "
      "`bash analysis/formulas/run_all.sh`. The design was pre-specified in `analysis/formulas/plan.md` (committed before any "
      "result was computed). Percentages are densities (share of word tokens covered); brackets are 95% intervals. "
      "Confirmatory tests are C1-C5 (2019 final) and their replication R1, R3-R5 (2023 final); everything else is exploratory.")
    A("")
    A("## 0. Data")
    A("")
    A(table(["corpus", "role", "medium", "utterances", "tokens (this tokeniser)"], [
        [f"`{C.MAIN}`", "MAIN, in-sample", "TV speech (ASR)", meta["utterances_2019"], meta["tokens_2019"]],
        [f"`{C.HELDOUT}`", "HELD-OUT", "TV speech (ASR)", meta["utterances_2023"], meta["tokens_2023"]],
        ["18 `tv_pool_*`", "reference pool (identification)", "TV speech (ASR)", meta["utterances_pool"], meta["tokens_pool"]],
        [f"`{C.TEXT}`", "written contrast", "written live text", mmeta["cornell_updates"], mmeta["cornell_tokens"]],
        ["press answers", "spoken non-commentary baseline", "speech (stenographic transcript)", mmeta["press_answers"], mmeta["press_tokens"]],
    ]))
    A("")
    A(f"Utterance = one rally clip's de-duplicated, corrected ASR text (`text_corrected`; empty clips dropped), one live-text update, or one "
      f"player answer. Mean tokens per utterance: " + ", ".join(f"{k} {v:.1f}" for k, v in mmeta["mean_tokens_per_utterance"].items()) + ". "
      f"The press answers (Cornell release, {mmeta['press_interviewees']} interviewees, 2007-2015) are human transcripts of a non-live genre; "
      f"`corpus/SOURCES.md` lists them as DON'T USE *as commentary*; they are used only as a baseline (FOR_HUMAN.md).")
    A("")
    A("## Key results")
    A("")
    c1k, c2k = cf("C1"), cf("C2")
    tvsp = medv("D5i_matched_2019_size", "tv_pool_all", "splithalf", "a")
    txsp = medv("D5i_matched_2019_size", C.TEXT, "splithalf", "a")
    prsp = medv("D5i_matched_2019_size", "press_answers", "splithalf", "a")
    nrej = sum(1 for r in conf if r["family"] == "2019" and r["reject_at_0.05"] == "True")
    nrej23 = sum(1 for r in conf if r["family"] == "2023_replication" and r["reject_at_0.05"] == "True")
    A(f"* (a) exact formulas cover {pc(d1['density'])}% {ci(d1['ci_lo'], d1['ci_hi'])} of the 2019 final in-sample, {pc(d2['density'])}% "
      f"{ci(d2['ci_lo'], d2['ci_hi'])} split-half, and {pc(d3['density'])}% {ci(d3['ci_lo'], d3['ci_hi'])} when identified on 18 other matches; "
      f"(a)+(b) {pc(d1b['density'])}%, {pc(d2b['density'])}%, {pc(d3b['density'])}%. Formulas of the 2019 final cover {pc(d3x['density'])}% "
      f"{ci(d3x['ci_lo'], d3x['ci_hi'])} of the held-out 2023 final ((a)+(b) {pc(d3xb['density'])}%).")
    A(f"* Baselines with the same procedure: shuffled words {pc(sh_in['density'])}% in-sample, {pc(sh_sp['density'])}% split-half. "
      f"At matched size (split-half, {T19:,} tokens) TV commentary (18-match pool subsamples) {pc(tvsp['mean'])}%, written live text {pc(txsp['mean'])}%, "
      f"press answers {pc(prsp['mean'])}%.")
    A(f"* Confirmatory family (Holm): {nrej} of 6 null hypotheses rejected for 2019, {nrej23} of 5 in the 2023 replication: " +
      "; ".join(f"{r['id']} {r['verdict']}" for r in conf if r["reject_at_0.05"] == "True") + " (section 4).")
    timing = [cf(x) for x in ("C3a", "C3b", "C4", "C5")]
    sur = [float(r["share_surname"]) for r in ext]
    epi = [float(r["share_epithet"]) for r in ext]
    A(f"* Naming: the bare surname is {pc(min(sur), 0)}-{pc(max(sur), 0)}% of each player's references and descriptive epithets "
      f"{pc(min(epi), 0)}-{pc(max(epi), 0)}% (section 5). " +
      ("No timing test was significant: neither formulaic density (C3a, C3b) nor the choice (C4) or length (C5) of names tracks the time "
       "available around the point." if not any(r["reject_at_0.05"] == "True" for r in timing) else
       "Timing tests rejected: " + ", ".join(r["id"] for r in timing if r["reject_at_0.05"] == "True") + "."))
    A("")
    A("## 1. Definitions (exact)")
    A("")
    A("**Tokens.** NFKC; curly quotes to `'`; hyphens, dashes and `/` to space; lower-case; token = `[a-z0-9]+(?:'[a-z0-9]+)*` "
      "(clitics stay attached: `it's`, `federer's`); other punctuation dropped; digits kept verbatim (`15`, `40`); number words not normalised. "
      "N-grams never cross an utterance boundary but do cross punctuation inside an utterance (WhisperX punctuation is unreliable). "
      "STOP = a frozen list of 182 function words (`common.py`); digits and player names are never STOP.")
    A("")
    A("**(a) Formula.** An n-gram (2 <= n <= 12) is a formula of an identification set I if it occurs in at least m = 2 distinct utterances "
      "of I and is not stop-only. **Density** of a measurement set M = share of M's tokens lying inside at least one occurrence (in M) of a "
      "formula of I of length >= n_min (n_min = 2). In-sample (I = M) this is Duggan's criterion 'repeated elsewhere in the text'. "
      "Held-out (I and M disjoint) it is the share of M that reuses phrases already established as repeated in I.")
    A("")
    A("**(b) System.** A frame is an n-gram (2 <= n <= 6) with exactly one slot. Slot types: `<NAME>` (a first name or surname of any of the "
      "40 players of the 20 TennisVL matches, possessive stripped), `<NUM>` (a digit string or `love fifteen thirty forty deuce`), `<_>` "
      "(any token). A frame is a system of I if it occurs >= 3 times in >= 3 utterances of I with >= 2 distinct fillers, has >= 1 non-STOP "
      "fixed token, and, if the slot is `<_>`, the slot is internal (fixed tokens on both sides). (a)+(b) density = share of tokens covered "
      "by a formula or by an occurrence of a system of I (any filler of the right type).")
    A("")
    A("**Designs.** D1 in-sample (I = M). D2 split-half: I = odd clips, M = even clips and vice versa (pooled; CI resamples within halves). "
      "D3 held-out across matches: I = the 18 pool matches, M = the 2019 final; I = the 2019 final, M = the 2023 final. "
      "D4 per stream (leave-one-stream-out identification; and 1,500-token subsamples). D5 per medium at matched size. "
      "D6 per context. D7 shuffled-word baseline (tokens of the 2019 stream permuted over positions, utterance lengths kept).")
    A("")
    A("**Contexts.** `phase` is the corpus's regex tag (`between_points` = the whole clip text is a score call; `changeover` = a cue word); it "
      "is defined from the text itself, so its density contrast is partly definitional. `dead_time_before_s` = PBP time from the end of the "
      "previous rally to this point's first serve. `time_after_s` = `dead_time_before_s` of the next point (or the gap to the second serve for a "
      "first-serve-fault clip), used because the clip transcript runs past the clip end (corpus/README section 4). Terciles are cut per stream: "
      f"2019 dead time before {c3['cuts_2019']['dead_time_before_s'][0]:.1f} / {c3['cuts_2019']['dead_time_before_s'][1]:.1f} s, "
      f"time after {c3['cuts_2019']['time_after_s'][0]:.1f} / {c3['cuts_2019']['time_after_s'][1]:.1f} s; "
      f"2023 {c3['cuts_2023']['dead_time_before_s'][0]:.1f} / {c3['cuts_2023']['dead_time_before_s'][1]:.1f} s and "
      f"{c3['cuts_2023']['time_after_s'][0]:.1f} / {c3['cuts_2023']['time_after_s'][1]:.1f} s. Score situation of the aligned PBP point: "
      "match point > set point > break point > other tie-break point > deuce/advantage > other.")
    A("")
    A(f"**Uncertainty.** Densities: percentile bootstrap over utterances of M (B = {meta['B']}), with I's inventory held fixed, so the "
      "interval covers sampling of the measured text, not uncertainty in formula identification. Subsample designs report the mean and "
      "2.5-97.5% range over replicates. Tests: see section 4; Holm-Bonferroni within the confirmatory family and within the replication family.")
    A("")
    A("## 2. Formulas (a) and systems (b) in the 2019 final")
    A("")
    A(f"{fsum['formula_types_stop_filtered']} formula types (n = 2..12, stop-only n-grams excluded; {fsum['formula_types_unfiltered']} without the "
      f"filter). In-sample (a) density {pc(d1['density'])}% {ci(d1['ci_lo'], d1['ci_hi'])}. "
      f"{fsum['types_shared_with_any_pool_stream']} of the {fsum['formula_types_stop_filtered']} types also occur in at least one of the 18 other "
      f"matches, and {fsum['types_in_2023']} in the 2023 final.")
    A("")
    A("**Table 2.1. Formulas by length n (in-sample, 2019).** Coverage = share of all 2019 tokens covered by formulas of exactly this length.")
    A("")
    A(table(["n", "filter", "types", "occurrences", "coverage %", "types in >= 1 / >= 3 / >= 9 pool matches", "types in 2023"],
            [[r["n"], r["filter"], r["formula_types"], r["occurrences"], pc(r["coverage_share"]),
              f"{r['types_in_ge1_pool_streams']} / {r['types_in_ge3_pool_streams']} / {r['types_in_ge9_pool_streams']}", r["types_in_2023"]]
             for r in byn]))
    A("")
    A("**Table 2.2. Maximal match** (each token assigned the length of the longest formula covering it; 0 = uncovered).")
    A("")
    A(table(["longest formula covering the token", "tokens", "%"], [[r["longest_formula_len"], r["tokens"], pc(r["share"])] for r in mm]))
    A("")
    bins = [(0, 0), (1, 2), (3, 8), (9, 18)]
    A("**Table 2.3. Within vs across matches**: 2019 formula types by the number of other matches (pool streams, each a different "
      "match and possibly a different broadcaster) in which they occur.")
    A("")
    A(table(["pool matches attesting the formula", "2019 formula types"],
            [[f"{a}" if a == b else f"{a}-{b}", sum(int(r["formula_types_2019"]) for r in cs if a <= int(r["pool_streams_attested"]) <= b)]
             for a, b in bins]))
    A("")
    A("**Table 2.4. The 25 most widespread formulas** (by distinct utterances; full list with excerpts in `results/formulas_2019.tsv`).")
    A("")
    A(table(["rank", "formula", "n", "utterances", "occurrences", "coverage %", "pool matches"],
            [[r["rank"], f"`{r['formula']}`", r["n"], r["utterances"], r["occurrences"], pc(r["coverage_share"], 2), r["pool_streams_attested"]]
             for r in f19[:25]]))
    A("")
    A(f"**Systems.** {ssum['systems']} systems: " + ", ".join(f"{k} {v}" for k, v in ssum["systems_by_slot_type"].items()) + ". By length: " +
      ", ".join(f"n={r['n']} {r['slot_type']} {r['systems']}" for r in sbt) + ".")
    A("")
    A("**Table 2.5. The 25 most widespread systems** (`<_>` open slot; full list in `results/systems_2019.tsv`). "
      "'beyond (a)' = share of all tokens covered by the frame but by no formula.")
    A("")
    A(table(["rank", "frame", "slot", "occurrences", "utterances", "fillers (top)", "coverage %", "beyond (a) %", "pool matches"],
            [[r["rank"], f"`{r['frame']}`", r["slot_type"], r["occurrences"], r["utterances"],
              "; ".join(r["top_fillers"].split("; ")[:5]), pc(r["coverage_share"], 2), pc(r["coverage_beyond_a_share"], 2),
              r["pool_streams_attested"]] for r in s19[:25]]))
    A("")
    tbm = rcsv("formulas_top_by_medium.csv")
    A("**Table 2.6. Most widespread formulas of n >= 3 in each corpus** (exploratory; each corpus identified on itself, whole corpus; "
      "utterance counts and rate per 1,000 tokens; n-grams contained in a longer listed one with the same count dropped).")
    A("")
    cn = ["tv_2019wimF", "tv_pool_18_matches", "text_cornell"]
    rows = []
    for k in range(1, 16):
        row = [k]
        for c_ in cn:
            r = next((x for x in tbm if x["corpus"] == c_ and int(x["rank"]) == k), None)
            row.append(f"`{r['formula']}` {r['utterances']} ({r['utterances_per_1000_tokens']})" if r else "")
        rows.append(row)
    A(table(["rank", "2019 final", "TV pool (18 matches)", "Cornell live text"], rows))
    A("")
    A(f"ASR in score calls: of {ssum['score_call_frame_filler_occurrences']} filler occurrences in two-token score-call frames, "
      f"{ssum['score_call_fillers_not_score_words']} are not possible score words (" +
      ", ".join(f"`{k}` {v}" for k, v in list(ssum["non_score_fillers"].items())[:5]) +
      "), i.e. 'forty' heard as `14`, 'thirty' as `13`, 'fifteen' as `50`. These split exact score-call formulas but are absorbed by `<NUM>` systems.")
    A("")
    A("## 3. Formulaic density")
    A("")
    A("**Table 3.1. Main densities** (TV speech, finals).")
    A("")
    rows = []
    for r in dm:
        if r["measure"] != "a":
            continue
        rb = dmv(r["design"], r["identified_on"], r["measured_on"], "a+b")
        rows.append([r["design"], r["identified_on"], r["measured_on"], r["tokens_measured"], f"{pc(r['density'])} {ci(r['ci_lo'], r['ci_hi'])}",
                     f"{pc(rb['density'])} {ci(rb['ci_lo'], rb['ci_hi'])}"])
    A(table(["design", "identified on", "measured on", "tokens", "(a) %", "(a)+(b) %"], rows))
    A("")
    A(f"In-sample and held-out figures differ as the sizes of I lead one to expect: the 2019 final reuses {pc(d1['density'])}% of its tokens within itself, "
      f"{pc(d2['density'])}% when formulas must come from the other half of the match, and {pc(d3['density'])}% when they come from 18 other matches "
      f"({TP:,} tokens, about {TP / T19:.0f} times the final). Density therefore depends strongly on the size of I; compare only like with like.")
    A("")
    A("**Table 3.2. Baselines and media at matched size** (same procedure, each corpus identified on itself; mean and 2.5-97.5% over replicates).")
    A("")
    rows = [["shuffled words, 2019 (D7)", f"{T19:,}", f"{pc(sh_in['density'])} {ci(sh_in['ci_lo'], sh_in['ci_hi'])}",
             f"{pc(sh_sp['density'])} {ci(sh_sp['ci_lo'], sh_sp['ci_hi'])}", "-"],
            ["2019 final (single match)", f"{T19:,}", f"{pc(d1['density'])} {ci(d1['ci_lo'], d1['ci_hi'])}",
             f"{pc(d2['density'])} {ci(d2['ci_lo'], d2['ci_hi'])}", f"{pc(d3['density'])} {ci(d3['ci_lo'], d3['ci_hi'])} (pool -> 2019)"]]
    labels = {"tv_pool_all": "TV pool subsample (18 matches)", C.TEXT: "Cornell live text (written)", "press_answers": "press answers (spoken, not commentary)"}
    for corpus in ("tv_pool_all", C.TEXT, "press_answers"):
        a = medv("D5i_matched_2019_size", corpus, "insample", "a")
        b = medv("D5i_matched_2019_size", corpus, "splithalf", "a")
        if corpus == "tv_pool_all":
            h = "see D3/D4"
        else:
            hv = medv("D5ii_heldout_disjoint_groups", corpus, "heldout", "a")
            h = f"{pc(hv['mean'])} {ci(hv['p2_5'], hv['p97_5'])}"
        rows.append([labels[corpus], f"{T19:,}", f"{pc(a['mean'])} {ci(a['p2_5'], a['p97_5'])}", f"{pc(b['mean'])} {ci(b['p2_5'], b['p97_5'])}", h])
    A(table(["corpus", "tokens measured", "in-sample (a) %", "split-half (a) %", f"held-out (a) %, I = {TP:,} tokens, disjoint groups"], rows))
    A("")
    rows = []
    for corpus in ("tv_pool_all", C.TEXT, "press_answers"):
        a = medv("D5i_matched_2019_size", corpus, "insample", "a+b")
        b = medv("D5i_matched_2019_size", corpus, "splithalf", "a+b")
        g = medv("D5iii_insample_pool_size", corpus, "insample", "a")
        rows.append([labels[corpus], f"{pc(a['mean'])} {ci(a['p2_5'], a['p97_5'])}", f"{pc(b['mean'])} {ci(b['p2_5'], b['p97_5'])}",
                     f"{pc(g['mean'])} {ci(g['p2_5'], g['p97_5'])}"])
    A("**Table 3.3. (a)+(b) at 2019 size, and (a) in-sample at pool size** (" + f"{TP:,}" + " tokens).")
    A("")
    A(table(["corpus", "in-sample (a)+(b) %", "split-half (a)+(b) %", "in-sample (a) % at pool size"], rows))
    A("")
    A("At pool size the TV 'subsample' is the whole pool, so its replicates are identical. "
      "Written live text is identified and measured only on itself. The held-out Cornell and press figures draw I and M from disjoint "
      "player pairs and interviewees respectively; the TV analogue is pool -> 2019, where M is one whole match.")
    A("")
    A("**Table 3.4. Per stream** (each stream = one match with one unnamed TV broadcaster; broadcaster, match and commentators are confounded). "
      "Leave-one-out: I = the pool without this stream (for the finals: the whole pool). 1,500-token columns: mean over 200 random subsamples.")
    A("")
    rows = []
    streams = sorted({r["stream"] for r in dstr}, key=lambda s: (s.startswith("tv_pool"), s.startswith("press"), s.startswith("text"), s))
    for s in streams:
        def g(design, meas):
            return next((r for r in dstr if r["stream"] == s and r["design"] == design and r["measure"] == meas), None)
        lo = g("D4i_leave_one_stream_out", "a")
        i15 = g("D4ii_insample_1500", "a")
        s15 = g("D4ii_splithalf_1500", "a")
        rows.append([s.replace("tv_pool_", "pool: ")[:60], lo["tokens_measured"] if lo else "-",
                     f"{pc(lo['density'])} {ci(lo['ci_lo'], lo['ci_hi'])}" if lo else "-",
                     f"{pc(i15['density'])} {ci(i15['ci_lo'], i15['ci_hi'])}", f"{pc(s15['density'])} {ci(s15['ci_lo'], s15['ci_hi'])}"])
    A(table(["stream", "tokens", "leave-one-out held-out (a) %", "in-sample (a) %, 1,500 tokens", "split-half (a) %, 1,500 tokens"], rows))
    A("")
    A("**Table 3.5. Per context, 2019 final** ((a) density; in-sample = formulas from the whole 2019 stream; pool = formulas from the 18 other matches).")
    A("")
    ctx_names = {"phase": "phase tag (heuristic)", "dtb_terc": "dead time before (tercile)", "ta_terc": "time after (tercile)",
                 "role": "clip role", "score": "score situation"}
    for stream in (C.MAIN, C.HELDOUT):
        rows = []
        for ctx in ("phase", "dtb_terc", "ta_terc", "role", "score"):
            groups = sorted({r["group"] for r in dctx if r["stream"] == stream and r["context"] == ctx})
            for gname in groups:
                def gv(ident, meas):
                    return next(r for r in dctx if r["stream"] == stream and r["context"] == ctx and r["group"] == gname
                                and r["identified_on"] == ident and r["measure"] == meas)
                a, p, pb = gv("in_sample", "a"), gv("pool", "a"), gv("pool", "a+b")
                rows.append([ctx_names[ctx], gname, a["utterances"], a["tokens"], f"{pc(a['density'])} {ci(a['ci_lo'], a['ci_hi'])}",
                             f"{pc(p['density'])} {ci(p['ci_lo'], p['ci_hi'])}", f"{pc(pb['density'])} {ci(pb['ci_lo'], pb['ci_hi'])}"])
        if stream == C.HELDOUT:
            A("**Table 3.6. Per context, 2023 final (held-out match).**")
            A("")
        A(table(["context", "group", "utterances", "tokens", "in-sample (a) %", "pool (a) %", "pool (a)+(b) %"], rows))
        A("")
    A("**Table 3.7. Sensitivity analyses** (2019 unless stated; S-numbers as in plan.md section 8).")
    A("")
    rows = []
    for r in ds:
        if r["measure"] != "a":
            continue
        rb = next(x for x in ds if x["design"] == r["design"] and x["identified_on"] == r["identified_on"] and x["measured_on"] == r["measured_on"]
                  and x["variant"] == r["variant"] and x["measure"] == "a+b")
        rows.append([r["variant"], r["design"], f"{r['identified_on']} -> {r['measured_on']}", f"{pc(r['density'])} {ci(r['ci_lo'], r['ci_hi'])}",
                     f"{pc(rb['density'])} {ci(rb['ci_lo'], rb['ci_hi'])}"])
    A(table(["variant", "design", "I -> M", "(a) %", "(a)+(b) %"], rows))
    A("")
    A(f"S5 masks {pc(meta['S5_masked_token_share_2019'])}% of 2019 tokens as umpire/Hawk-Eye/announcer calls (score calls are not masked: "
      "the umpire and the commentators both say them and the transcript does not tell them apart).")
    A("")
    an = rjson("asr_noise_summary.json")
    lv = an["levels"]
    A(f"**Table 3.8. POST HOC exploratory: injected ASR-like substitution noise** (added after C1/C2 were seen; plan.md addendum). Each token "
      f"replaced with probability e by a token drawn from the TV-pool unigram distribution, in both I and M; (a) density, mean "
      f"[2.5-97.5%] over {an['R_split']} (split-half) or {an['R_held']} (held-out) replicates. e = {lv[1]} is the corpus's hand-read lower bound on "
      "the TV error rate. For TV rows e is noise added on top of the ASR errors already present.")
    A("")
    rows = []
    for design, corpus, label in (("splithalf_matched", "tv_pool_all", "split-half, TV pool subsample"),
                                  ("splithalf_matched", C.TEXT, "split-half, Cornell text"),
                                  ("splithalf_matched", "press_answers", "split-half, press answers"),
                                  ("heldout", "tv_pool_to_2019", "held-out, TV pool -> 2019"),
                                  ("heldout", C.TEXT, "held-out, Cornell text"),
                                  ("heldout", "press_answers", "held-out, press answers")):
        row = [label]
        for e in lv:
            cell = an["cells"].get(f"{design}|{corpus}|{e}")
            row.append(f"{pc(cell['mean'])} [{pc(cell['p2_5'])}, {pc(cell['p97_5'])}]" if cell else "-")
        rows.append(row)
    A(table(["design, corpus"] + [f"e = {e}" for e in lv], rows))
    A("")
    tv0 = an["cells"][f"splithalf_matched|tv_pool_all|0.0"]["mean"]
    cross = []
    for corpus, label in ((C.TEXT, "Cornell text"), ("press_answers", "press answers")):
        hits = [e for e in lv if an["cells"][f"splithalf_matched|{corpus}|{e}"]["mean"] <= tv0]
        cross.append(f"{label}: " + (f"falls to the TV level ({pc(tv0)}%) at e = {hits[0]}" if hits else
                                     f"stays above the TV level ({pc(tv0)}%) up to e = {lv[-1]}"))
    A("Split-half density under injected noise: " + "; ".join(cross) + ".")
    A("")
    A("## 4. Confirmatory tests and replication")
    A("")
    rows = []
    for r in conf:
        if r["id"] in ("C4", "R4"):
            est = f"D = {float(r['estimate_x']):.0f} vs null mean {float(r['estimate_y']):.1f} (null 95%: {float(r['estimate_y']) + float(r['diff_lo']):.0f}-{float(r['estimate_y']) + float(r['diff_hi']):.0f})"
        elif r["id"] in ("C5", "R5"):
            est = f"rho = {f3(r['estimate_x'])} (null 95%: {f3(r['diff_lo'])} to {f3(r['diff_hi'])})"
        else:
            est = f"{pc(r['estimate_x'])} vs {pc(r['estimate_y'])}; diff {pc(r['difference'])} pp {ci(r['diff_lo'], r['diff_hi'])}"
        rows.append([r["id"], r["hypothesis"], est, pv(r["p"]), pv(r["p_holm"]), r["verdict"]])
    A(table(["test", "hypothesis / statistic", "estimate", "p", "p (Holm)", "H0 at 0.05 (Holm)"], rows))
    A("")
    A("Holm-Bonferroni is applied within the 2019 family (C1, C2, C3a, C3b, C4, C5) and separately within the 2023 replication family "
      "(R1, R3a, R3b, R4, R5). C1/R1 compare a bootstrap distribution of the TV value with the press replicate distribution "
      "(10,000 random pairs); C2 pairs 200 replicate subsamples; C3 permutes tercile labels over utterances (5,000); C4/C5 use 10,000 "
      "permutations. Exploratory p-values elsewhere are unadjusted.")
    A("")
    c1, c2, c3a, c3b, c4, c5 = (cf(x) for x in ("C1", "C2", "C3a", "C3b", "C4", "C5"))

    def verdict(r):
        return r["verdict"]
    A(f"* **C1** (commentary more formulaic than non-commentary tennis speech, held-out): {verdict(c1)}; TV {pc(c1['estimate_x'])}% vs press "
      f"{pc(c1['estimate_y'])}% (difference {pc(c1['difference'])} points {ci(c1['diff_lo'], c1['diff_hi'])}). The TV measurement set is one match "
      "(names and topics concentrated), the press measurement set many interviewees; that asymmetry favours TV, so it cannot explain a TV deficit.")
    A(f"* **C2** (speech vs writing, split-half, matched size): {verdict(c2)}; TV pool {pc(c2['estimate_x'])}% vs Cornell live text {pc(c2['estimate_y'])}% "
      f"(difference {pc(c2['difference'])} points {ci(c2['diff_lo'], c2['diff_hi'])}).")
    nrep = int(mmeta["R_matched"])
    floor = 2 / (nrep + 1)
    if abs(float(c2["p"]) - floor) < 1e-9:
        A(f"  C2's p equals the resolution floor of {nrep} paired replicates (2/{nrep + 1}): all {nrep} paired differences have the same sign; "
          "the Holm-adjusted value is therefore conservative.")
    A(f"* **C3a/C3b** (less time, more formulas): {verdict(c3a)} / {verdict(c3b)}. Shortest minus longest tercile: dead time before "
      f"{pc(c3a['difference'])} points {ci(c3a['diff_lo'], c3a['diff_hi'])}; time after {pc(c3b['difference'])} points {ci(c3b['diff_lo'], c3b['diff_hi'])}.")
    A(f"* **C4** (thrift bound to available time): {verdict(c4)}; distinct expressions per player x slot x dead-time cell summed: "
      f"{float(c4['estimate_x']):.0f}, null mean {float(c4['estimate_y']):.1f}.")
    A(f"* **C5** (longer expressions with more time): {verdict(c5)}; rho = {f3(c5['estimate_x'])}.")
    A("* Replication on the 2023 final: " + "; ".join(f"{x} {cf(x)['verdict']}" for x in ("R1", "R3a", "R3b", "R4", "R5")) + ".")
    A("")
    A("**Table 4.2. Exploratory medium and baseline contrasts** (difference x - y in percentage points, interval over replicate pairs, unadjusted p).")
    A("")
    A(table(["id", "contrast", "x %", "y %", "diff", "p"],
            [[r["id"], r["hypothesis"], pc(r["estimate_x"]), pc(r["estimate_y"]), f"{pc(r['difference'])} {ci(r['diff_lo'], r['diff_hi'])}", pv(r["p"])]
             for r in medc]))
    A("")
    A("## 5. Noun-epithet systems")
    A("")
    tb = rsum["tokens_by_stream_player"]
    A(f"Referring expressions found: 2019 Federer {tb.get('tv_2019wimF:federer')}, Djokovic {tb.get('tv_2019wimF:djokovic')}; "
      f"2023 Djokovic {tb.get('tv_2023wimF:djokovic')}, Alcaraz {tb.get('tv_2023wimF:alcaraz')}. Third-person masculine pronouns "
      f"(excluded from the systems, counted): 2019 {rsum['pronouns_total']['tv_2019wimF']}, 2023 {rsum['pronouns_total']['tv_2023wimF']}. "
      f"{rsum['epithet_occurrences']} descriptive-epithet occurrences were assigned to a referent by hand verdict (`hand/epithet_referents.tsv`); "
      f"{rsum['epithets_unresolved']} unresolved.")
    A("")
    A("Inventory: full name, `mr` + surname (umpire), surname, first name, hypocoristic (`nole`, `rog`, `carlitos`), and descriptive epithets "
      "matched by a fixed regex family (`refexpr.py`). Slot: spaCy `" + rsum["spacy_model"] + "` dependency label of the expression's head, mapped "
      "as in plan.md section 5. Syllables: CMU Pronouncing Dictionary (vowel phonemes), vowel-group fallback for names not in it "
      "(`djokovic` 3; `nole` gets 1, which is wrong: 2), digits spelled out.")
    lo, hi = wilson(slotv["agree"], slotv["hand_labelled"])
    A("")
    A(f"Slot accuracy against my hand labels on a random sample: {slotv['agree']}/{slotv['hand_labelled']} = {pc(slotv['accuracy'])}% "
      f"(Wilson 95% {pc(lo)}-{pc(hi)}%). Disagreements (hand|parser): " +
      ", ".join(f"{k} {v}" for k, v in slotv["confusion_hand_vs_spacy"].items() if k.split("|")[0] != k.split("|")[1]) + ".")
    A("")
    import re as _re
    import refexpr as RX
    disc = rcsv("epithet_discovery.csv")
    pats = [p for p, cat in RX.PATTERNS if cat == "epithet"]
    outside = [d for d in disc if not any(_re.match(p, d["string"]) for p in pats)
               and (int(d["count"]) >= 2 or _re.search(r"champion|number one|seed|returner|player", d["string"]))]
    A("Audit: strings of the form `the (word){0,3} <person noun>` that the inventory does not match (count >= 2, or containing "
      "champion / number one / seed / player / returner), from `results/epithet_discovery.csv`; they are not added, to keep the pre-specified "
      "inventory: " + "; ".join(f"{d['stream'][3:7]} `{d['string']}` {d['count']}" for d in outside) + ".")
    A("")
    A("**Table 5.1. Every referring expression by player, with syllables and syntactic slot.**")
    A("")
    A(table(["match", "player", "category", "expression", "tokens", "syll.", "subj", "obj", "poss", "after prep", "voc/excl", "other"],
            [[r["stream"][3:7], r["player"], r["category"], f"`{r['expression']}`", r["tokens"], r["syllables_base"], r["subject"], r["object"],
              r["possessive"], r["after_preposition"], r["vocative_exclamation"], r["other"]] for r in inv]))
    A("")
    A("**Table 5.2. Length in syllables.**")
    A("")
    A(table(["match", "player", "syllables", "tokens", "expressions"], [[r["stream"][3:7], r["player"], r["syllables"], r["tokens"], r["expressions"]] for r in syl]))
    A("")
    A("**Table 5.3. Timing context** (dead-time terciles and score situation; tokens, distinct expressions, mean syllables, share of bare surname).")
    A("")
    rows = [[r["stream"][3:7], r["player"], r["context"], r["group"], r["tokens"], r["distinct_expressions"], r["mean_syllables"],
             pc(r["share_surname"], 0)] for r in byc if r["context"] in ("dtb_terc", "ta_terc", "score", "phase")]
    A(table(["match", "player", "context", "group", "tokens", "distinct", "mean syll.", "surname %"], rows))
    A("")
    A("**Table 5.4. Pronouns** (he, him, his, himself, he's, he'd, he'll) by dead-time tercile; attribution is heuristic "
      "(the single player named in the same utterance).")
    A("")
    A(table(["match", "group", "attributed to", "utterances", "pronouns"],
            [[r["stream"][3:7], r["group"], r["attributed_to"], r["utterances"], r["pronouns"]] for r in pron
             if r["context"] in ("all", "dtb_terc") and r["attributed_to"] in ("ANY", "federer", "djokovic", "alcaraz", "unattributed")]))
    A("")
    A("## 6. Economy (thrift) and extension")
    A("")
    A("Functionally equivalent = different expression types (normalised wording, possessive stripped) referring to the same player in the same "
      "syntactic slot and the same context cell. D = sum over player x slot x context cells of the number of distinct types. Null: context labels "
      "permuted among tokens within each player x slot stratum (10,000 permutations); one-sided p for 'fewer types than chance' (thrift). "
      "The utterance-level permutation (exploratory) keeps tokens of one utterance together.")
    A("")
    A(table(["match", "context", "players", "permutation", "status", "tokens", "cells", "D obs", "null mean [95%]", "p (fewer)", "p (two-sided)", "single-type cells %"],
            [[r["stream"][3:7], r["context"], r["players"], r["permutation"], r["status"], r["tokens"], r["cells_occupied"], r["D_observed"],
              f"{float(r['null_mean']):.1f} [{float(r['null_lo']):.0f}, {float(r['null_hi']):.0f}]", pv(r["p_one_sided_fewer"]), pv(r["p_two_sided"]),
              pc(r["thrift_index_single_type_cells"], 0)] for r in th]))
    A("")
    A("**Table 6.2. Extension** (size and range of each player's system).")
    A("")
    A(table(["match", "player", "tokens", "distinct expressions", "categories", "syllables min-max", "distinct lengths",
             "occupied cells (slot x dead-time x length class)", "surname %", "epithet %"],
            [[r["stream"][3:7], r["player"], r["tokens"], r["distinct_expressions"], r["distinct_categories"], f"{r['syllable_min']}-{r['syllable_max']}",
              r["distinct_syllable_lengths"], r["occupied_cells_slot_x_dtb_x_sylclass"], pc(r["share_surname"], 0), pc(r["share_epithet"], 0)] for r in ext]))
    A("")
    A("**Table 6.3. Length vs available time** (Spearman rho over expression tokens).")
    A("")
    A(table(["match", "time", "permutation", "status", "tokens", "rho", "null 95%", "p"],
            [[r["stream"][3:7], r["time"], r["permutation"], r["status"], r["tokens"], f3(r["rho"]), f"{f3(r['null_lo'])} to {f3(r['null_hi'])}", pv(r["p_two_sided"])]
             for r in lt]))
    A("")
    A("## 7. Top-10 formulae and systems for the composition brief (Phase 3)")
    A("")
    A("Pre-specified ranking: distinct utterances, after dropping items contained in a longer item with the same count. `official` = at least "
      "half of the occurrences fall inside umpire/Hawk-Eye patterns (S5). Situational slot: modal clip role and score situation, share of "
      "occurrences at pressure points (break/set/match/tie-break/deuce), median time after and before (s).")
    A("")
    for lst, title in ((top, "Table 7.1. Pre-specified top 10 (dominated by score calls and short phrases)."),
                       (top3, "Table 7.2. Exploratory top 10 restricted to formulas of n >= 3 and systems with >= 2 fixed tokens (more useful for composition).")):
        A(f"**{title}**")
        A("")
        A(table(["rank", "kind", "item", "utterances", "occurrences", "pool matches", "fillers (top)", "official", "modal role",
                 "pressure %", "median time after", "median dead time before"],
                [[r["rank"], r["kind"], f"`{r['item']}`", r["utterances"], r["occurrences"], r["pool_streams_attested"],
                  "; ".join(r["fillers"].split("; ")[:4]), r["official_call"], r["modal_clip_role"], pc(r["pressure_points_share"], 0),
                  r["median_time_after_s"], r["median_dead_time_before_s"]] for r in lst if r["list"] == "commentary_only"]))
        A("")
    A("## 8. Kuiper")
    A("")
    for r in kv:
        A(f"* {r['reference']} Status: **{r['status']}**. Record: {r['record_fetched']}. Confirms: {r['what_the_record_confirms']}.")
    A("")
    c1r, c2r = cf("C1"), cf("C2")
    timing = [cf(x) for x in ("C3a", "C3b", "C4", "C5")]
    tvsp = medv("D5i_matched_2019_size", "tv_pool_all", "splithalf", "a")
    prsp = medv("D5i_matched_2019_size", "press_answers", "splithalf", "a")
    txsp = medv("D5i_matched_2019_size", C.TEXT, "splithalf", "a")
    A("Relation to this analysis. Only the verified abstract of Kuiper and Haggo (1984) is used: livestock auctioneers 'use an oral "
      "formulaic technique', explained as 'a response to performance constraints which place a heavy load on short term memory', and the "
      "difference from ordinary speech is 'one of degree, not kind'. Two of our results bear on this.")
    A("")
    order = sorted([("TV commentary", float(tvsp["mean"])), ("press answers", float(prsp["mean"])), ("written live text", float(txsp["mean"]))],
                   key=lambda x: -x[1])
    A(f"* Degree. On one scale and one procedure, at matched size, split-half (a) density ranks " +
      " > ".join(f"{n} {pc(v)}%" for n, v in order) + f"; held-out, TV {pc(c1r['estimate_x'])}% vs press {pc(c1r['estimate_y'])}% (C1: "
      f"{c1r['verdict']}). The commentary is {float(d1['density']) / float(sh_in['density']):.1f} times as repetitive as its own words shuffled "
      f"({pc(d1['density'])}% vs {pc(sh_in['density'])}% in-sample), so its repetition is not an artefact of word frequencies; " +
      ("but on this measure it is not more formulaic than the spontaneous answers of players in post-match press conferences, and it is "
       "less so than the written live text. On a 'degree' scale this TV commentary sits at the low end, not with the auctioneers "
       "(subject to the ASR caveat quantified in Table 3.8)."
       if float(tvsp["mean"]) < float(prsp["mean"]) else "and more so than unscripted tennis talk, consistent with a difference of degree."))
    A(f"* Performance constraint. If formulas relieve time pressure, density and naming should shift toward the clips with the least "
      f"available time. Tests: " + "; ".join(f"{r['id']} {r['verdict']}" for r in timing) + ". "
      f"With clip-level text, and between-point dead times whose 2019 terciles are cut at "
      f"{c3['cuts_2019']['dead_time_before_s'][0]:.0f} and {c3['cuts_2019']['dead_time_before_s'][1]:.0f} s, tennis television may not impose the "
      "continuous load described for auctioneers; race calling, the obvious high-load comparison, cannot be drawn on here because those "
      "sources are verified only bibliographically (Kuiper 2009, ch. 2) or not at all (Kuiper and Austin [unverified]).")
    A("")
    A("## 9. Limitations")
    A("")
    A(f"1. **ASR.** The text is WhisperX output with no audio; the word error rate is unknown. The corpus's hand-read lower bound is "
      f"{asr['hand_sample']['total_per_1000_words']:.0f} errors per 1,000 words (Wilson 95% {asr['hand_sample']['wilson95_ci_per_1000_total'][0]:.0f}-"
      f"{asr['hand_sample']['wilson95_ci_per_1000_total'][1]:.0f}, `corpus/reports/asr_proxy.json`); plausible-word substitutions are invisible. "
      "ASR errors cut both ways: they break true repetitions (score calls `14 30` for '40-30'), and a systematic mishearing can create a false one. "
      "Score-call systems absorb the digit confusions; exact formulas do not.")
    A("2. **Clip-level text.** No word times: a clip's text spans the rally and the following dead time, so 'available time' is assigned per "
      "clip, not per phrase. The phase tags are text-based heuristics; `between_points` clips are score calls by definition.")
    A("3. **One broadcaster per match, no speaker labels.** Commentator identity, broadcaster and match are confounded in every per-stream "
      "comparison; the umpire's and Hawk-Eye's voices are inside the text (S5 masks only the clearest calls; score calls stay).")
    A("4. **De-duplication.** Exact repeats of the previous clip's text (within 3 clips) were removed by the corpus builder; shorter overlaps "
      "remain. S4 (repeats at least 4 clips apart) and S1 (`text_dedup`) bound the effect.")
    A("5. **Size dependence.** Density rises with the size of the identification set; only size-matched comparisons are interpretable "
      "(Tables 3.2-3.4). The 2019 final is one match; the pool, Cornell and press samples mix many events, which lowers their repetition of "
      "names and topics.")
    A("6. **Media contrast.** Speech vs writing is confounded with matches, outlets, period (Cornell and press are older) and transcription "
      "(ASR vs editorial text vs stenography).")
    A("7. **Referring expressions.** The epithet inventory is a fixed regex family checked against a discovery list "
      "(`results/epithet_discovery.csv`); referents of descriptive epithets and the slot validation are single-annotator hand verdicts. "
      "Pronouns are not resolved. The surname dominates every cell, so the thrift test has little room to detect structure.")
    A("8. **CIs** condition on the formula inventory; split-half and random-split distributions (Table 3.7) show the identification variability.")
    A("9. **Transcription conventions.** Press answers are edited stenographic transcripts and Cornell is edited prose; both are cleaner than ASR. "
      "Utterances differ in length across corpora (mean tokens above); because a formula must recur in two distinct utterances, the shorter TV "
      "utterances make that criterion, if anything, easier for TV to meet.")
    A("")
    A("## 10. Files")
    A("")
    A("`plan.md` (pre-specification), `common.py` (tokeniser, STOP, identification, coverage, contexts), `refexpr.py`, scripts `f01`-`f08`, "
      "`make_report.py`, `run_all.sh`; hand inputs in `hand/`; all tables in `results/` (`formulas_2019.tsv`, `systems_2019.tsv`, "
      "`top10_for_brief.csv`, `density_*.csv`, `confirmatory.csv`, `refexpr_*.csv`, `thrift_*.csv`). Transcript excerpts in committed "
      f"files are at most 12 words (formulas {fsum['excerpt_words_written']} words in total, systems {ssum['excerpt_words_written']}) or 15 words "
      "(hand files, epithet candidates).")
    # guard: committed transcript excerpts must be at most 15 words
    for name, col in (("formulas_2019.tsv", "example_excerpt_max12w"), ("systems_2019.tsv", "example_excerpt_max12w"),
                      ("epithet_candidates.tsv", "excerpt_max15w"), ("../hand/epithet_referents.tsv", "excerpt_max15w")):
        for r in rcsv(name, "\t"):
            assert len(r[col].split()) <= 15, (name, r[col])
    (C.HERE / "report.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("report.md written:", len(L), "lines")


if __name__ == "__main__":
    main()
